### ISSUE TITLE
Missing localization file for en-us.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/interface#1446]
**Bug Description**
GET https://app.uniswap.org/locales/en-US.json 404

**Steps to Reproduce**

1. Open https://app.uniswap.org
2. Notice that it tries to fetch locales/en-US.json and fails.

**Expected Behavior**
All resources that are attempted to be fetched successfully fetch.

**Additional Context**
Don't waste resources and clog up the browser console with errors for things that you know will never exist.

**Comment by tatulea** [comment]
Same error is now present in v5.30.0.

`Module not found: Error: Can't resolve './i18n/locales/translations' in '~/interface/apps/web/src'`
