### ISSUE TITLE
Add range selection slider and liquidity visualization

### ISSUE THREAD

**Issue by callil** [Uniswap/interface#1459]
We should integrate an improved version of the liquidity distribution visualization combined with a range slider for the add liquidity page. 

<img width="486" alt="Screen Shot 2021-05-06 at 2 59 11 PM" src="https://user-images.githubusercontent.com/1355319/117351360-a0fbd080-ae7b-11eb-843d-612fbecea187.png">

#1435

**Comment by BOR4** [comment]
follow up on this.

Can it also calculate capital efficiency?

**Comment by aviRon012** [comment]
It would be nice if you could see the percentage of the liquidity between any two prices, and if you could see the median and the 25% and 75% markings of the liquidity distribution.
I came to comment to talk about this issue but someone thought of it before me.

**Comment by asood123** [comment]
Need to get data first (also needed for charts)
