### ISSUE TITLE
Uniswap - ETH & USDT to Shib Via Coinbase Wallet

### ISSUE THREAD

**Issue by CraigM2020** [Uniswap/interface#1503]
Hi there,

I was wondering if you could help me. 

I recently put through a transaction to swap USDT and ETH to SHIB via my Coinbase Wallet.

On EtherScan, it looks like the transaction has been successful. The gas used by the transaction is less than the gas limit and the transaction doesn’t appear to be stuck in pending.

The SHIB price has gone up significantly and I’m concerned that I don’t have anything to show for the transaction. Can you please help / assist.

Thanks,
Craig

**Comment by callil** [comment]
@CraigM2020 Head over to the community discord to get some assistance: https://discord.gg/FCfyBSbCU5
