### ISSUE TITLE
Position inactive even though according to displayed data it should be in range

### ISSUE THREAD

**Issue by BOR4** [Uniswap/interface#1667]
**Bug Description**
I think this is issue with rounding. Pic should explain it all.

**Steps to Reproduce**

![image](https://user-images.githubusercontent.com/40821065/119056355-da2f5700-b9ca-11eb-912d-10e159d7bba1.png)

min: 0.999
max 1.001

current: 0.99906

According to numbers above it should be in range but it is not. I think issue is that 0.999 is not 0.99900 but something above 0.99906.
**Expected Behavior**
Displayed numbers and status match

**Additional Context**
Think about adding more decimals for all the stablecoin pairs.

**Comment by zjunyi** [comment]
Same issue, the UI glitches out when attempting to add liquidity when the current price very close e.g. 0.99906 when adding to 0.999-1.001.  Goes away once >0.9991, so probably some kind of rounding error.

**Comment by just-toby** [comment]
i'm not seeing this issue anymore
