### ISSUE TITLE
Show spot price on token select

### ISSUE THREAD

**Issue by callil** [Uniswap/interface#1712]
We should consider fetching and displaying the spot price of the pair as soon as a token is selected rather than relying on the use to input a value. This will be useful for people who are checking the current market price of a token pair and reduce clicks/actions.

**Comment by justindomingue** [comment]
Would need to make currencyAmount?.currency non-null to get a price.

https://github.com/Uniswap/uniswap-interface/blob/main/src/hooks/useUSDCPrice.ts#L59

**Comment by moodysalem** [comment]
> Would need to make currencyAmount?.currency non-null to get a price.
> 
> https://github.com/Uniswap/uniswap-interface/blob/main/src/hooks/useUSDCPrice.ts#L59

You can just use the other hook, `useUSDCPrice` (ignoring performance of fetching this twice in one component)

**Comment by MStreet3** [comment]
Is there a design of what this should look like?  not clear from the issue where the spot price should appear.

**Comment by justindomingue** [comment]
@MStreet3 see the screenshots below from app.uniswap.org. The spot price for ETH only appears after I input 1.0. The spot price is independent of the input amount so we could always show it when a token is selected.

### No input amount
(change requested is to make it show the spot price)
![image](https://user-images.githubusercontent.com/1284993/120536181-b4298f80-c398-11eb-942e-f7fcf2b5c452.png)

### With input amount
![image](https://user-images.githubusercontent.com/1284993/120536160-ae33ae80-c398-11eb-9c3f-1f559b085799.png)

**Comment by MStreet3** [comment]
Hi, I'm trying to resolve this issue via this PR https://github.com/Uniswap/uniswap-interface/pull/1816

**Comment by prakashsanker** [comment]
@justindomingue  is this issue still open? Can I take a stab at it?

**Comment by ghgoodreau** [comment]
Took a stab at this since it was dead for a bit. Please take a look! #3909
