### ISSUE TITLE
scroll to top when navigating / remember scroll when going back

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/interface#1728]
we need to fix scroll behavior when navigating between pages

**Comment by moodysalem** [comment]
chrome actually does this automatically, and some testing showed it works pretty well
https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration

ios safari, not so good

**Comment by willhennessy** [comment]
Steps to reproduce.

Browser:  Safari iOS mobile browser

### Bug:  scroll to top
1. visit https://app.uniswap.org/#/vote?chain=mainnet
2. scroll down to an old proposal such as proposal 1.1
3. Click on proposal 1.1

Intended behavior:  navigate to the proposal 1.1 page, with the scroll position at the top of the page so the user can read the proposal from the start.
Actual behavior:  navigates to the proposal 1.1 page, but the scroll position is further down in the middle of the page

### Remember scroll position when going back.
I cannot reproduce this.

**Comment by lynnshaoyu** [comment]
Hey @moodysalem, are we trying to scroll to top on every page navigation in the app, or just for the voting proposal page Will mentioned? 

Also, I believe the app is already remembering original scroll position when going back (click back button on browser) for both chrome and safari.
