### ISSUE TITLE
on/off labels do not work well in non-english languages

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/interface#1828]
**Bug Description**
<img width="196" alt="Screen Shot 2021-06-08 at 8 57 08 AM" src="https://user-images.githubusercontent.com/7897876/121198237-98f6ce00-c837-11eb-8735-ddab50714803.png">
<img width="158" alt="Screen Shot 2021-06-08 at 8 57 13 AM" src="https://user-images.githubusercontent.com/7897876/121198260-9d22eb80-c837-11eb-88ce-dfb5cf65e3ab.png">

In languages with longer text for on/off, the toggles look very different. Replace with something more responsive maybe

Assigning to Maggie in case this is already being worked on

**Comment by willhennessy** [comment]
hi @maggievalentine what would you recommend?

**Comment by maggievalentine** [comment]
agh... we might have to shift to an on/off toggle that uses color / iconography rather than text. can design some options

**Comment by infredible** [comment]
# Design guidance for this bug

## Overview
These changes should effect:
- transaction settings
- the token list
- position detail page
- positions page


### Remove text/copy from toggle
<img width="642" alt="CleanShot 2022-05-19 at 13 41 10@2x" src="https://user-images.githubusercontent.com/3887562/169400918-9d6437df-94f6-49f8-bc1f-e98b2e64b544.png">

### Make switch knob appear on right for "on" consistently throughout app
Currently, toggle switches appear inconsistently with the knob on either side to indicate "on" (current implementation)
<img width="260" alt="CleanShot 2022-05-19 at 13 42 04@2x" src="https://user-images.githubusercontent.com/3887562/169401057-c86ec7bf-10ab-4316-9be8-ad78bd7e83d0.png">
<img width="327" alt="CleanShot 2022-05-19 at 13 43 21@2x" src="https://user-images.githubusercontent.com/3887562/169401269-8fcc08f4-906d-4397-ad4e-6ac907a55a92.png">

The knob should be on the _right_ side for "on":
<img width="354" alt="CleanShot 2022-05-19 at 13 46 21@2x" src="https://user-images.githubusercontent.com/3887562/169401729-b8ad6cb2-cad7-4ff3-9e0f-d2c452a25163.png">
<img width="356" alt="CleanShot 2022-05-19 at 13 46 37@2x" src="https://user-images.githubusercontent.com/3887562/169401767-9ef512a3-ac33-476b-84e4-c3df039064a8.png">
<img width="822" alt="CleanShot 2022-05-19 at 13 46 58@2x" src="https://user-images.githubusercontent.com/3887562/169401829-2bbf17ee-66e3-496a-8ec9-c20b6e455036.png">
<img width="892" alt="CleanShot 2022-05-19 at 13 47 19@2x" src="https://user-images.githubusercontent.com/3887562/169401877-f83c7f8a-a65b-47eb-ab7e-c7ca68a17394.png">

### Positions page should use the same toggle switch
The current implementation has a text-based button for hiding and closing
<img width="695" alt="CleanShot 2022-05-19 at 13 50 11@2x" src="https://user-images.githubusercontent.com/3887562/169402287-257c4ae5-9aa3-4c9e-ab51-9769497c4595.png">

Change this to the same toggle components as above
<img width="669" alt="CleanShot 2022-05-19 at 13 50 57@2x" src="https://user-images.githubusercontent.com/3887562/169402382-94b8ff75-f0a6-488a-bf9c-38c3f30e055b.png">
<img width="654" alt="CleanShot 2022-05-19 at 13 51 07@2x" src="https://user-images.githubusercontent.com/3887562/169402389-75834c6b-e909-40e8-8010-c2245ad493b3.png">

**Comment by ghgoodreau** [comment]
I have implemented a new toggle in  https://github.com/Uniswap/interface/pull/3858 that I think is aligned with this spec.
