### ISSUE TITLE
ENS name avatar support

### ISSUE THREAD

**Issue by brantlymillegan** [Uniswap/interface#1884]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a UI improvement. Right now, when I Connect my wallet to the Uniswap App, it displays the ENS name in my reverse record on the top right, which is great. It shows an automatically generated image next to it, which is not very personal or readable.

**Describe the solution you'd like**
ENS records have an avatar record in which users can put a URL to an image. It would be great if after grabbing the ENS name from my reverse record, you then looked to see if the name had an avatar text record, and if so then displayed the image next to the ENS name instead of the automatically generated one. If the name doesn't have an avatar text record, then fall-back to the automatically generated image.

**Describe alternatives you've considered**
There aren't any

**Additional context**
Here's an example of the records of an ENS name with an avatar text record: https://app.ens.domains/name/brantly.art

Here's how it looks right now:
<img width="425" alt="Screen Shot 2021-06-19 at 12 44 11 PM" src="https://user-images.githubusercontent.com/30162762/122649504-1229d700-d0fc-11eb-877c-5d378ad57fcf.png">

Here's how it would look if you implemented what i outlined in this feature request:
![2](https://user-images.githubusercontent.com/30162762/122649530-35ed1d00-d0fc-11eb-9a24-508bf8e9e4bf.jpg)

**Comment by NoahZinsmeister** [comment]
closed by #2806
