### ISSUE TITLE
Add network parameter to uniswap URLs

### ISSUE THREAD

**Issue by rahul-kothari** [Uniswap/interface#1893]
**Is your feature request related to a problem? Please describe.**
I am working for the EF's Devcon ticketing team. We use uniswap as a way for users to pay for the tickets. And this devcon we are also integrating some L2 networks.

We basically create a uniswap URL and let user's pay through that. So for example:
https://uniswap.exchange/send?exactField=output&exactAmount={exact_amount}&outputCurrency={output_currency}&recipient={recipient_address}

Except this always defaults to Ethereum mainnet. So say, I wanted to do this on Rinkeby testnet or optimism, because there is no network parameter, the website defaults to ETH Mainnet and reports that the tokens are unrecognised. The user would have to then manually connect their wallet to the right network to see the tokens. This isn't just poor UX for the user but also potentially dangerous. The non-sophisticated user wouldn't even realise what went wrong and may end up paying on the wrong network.

**Describe the solution you'd like**
The URL to have a `network`/`chainId` parameter (default = 1).
So if a chainId is provided, then the UI should default to the appropriate network (instead of currently assuming it is always eth mainnet).

https://uniswap.exchange/send?exactField=output&exactAmount={exact_amount}&outputCurrency={output_currency}&recipient={recipient_address}&chainId=3

This would be super helpful for when uniswap scales to other L2s. 

**Additional context**
![image](https://user-images.githubusercontent.com/35169918/122901925-eef26800-d345-11eb-9640-861c34949895.png)
https://app.uniswap.org/#/swap?exactAmount=3500&outputCurrency=ETH&inputCurrency=0xc7AD46e0b8a400Bb3C915120d284AafbA8fc4735recipient=0xc7AD46e0b8a400Bb3C915120d284AafbA8fc4735&exactField=output

^ Convert DAI to ETH on Rinkeby testnet. However to a user, it would seem like there is nothing wrong here and end up paying on the wrong network.

**Comment by willhennessy** [comment]
Hi Rahul, thanks for the suggestion! @JFrankfurt  are we able to change the network on command like this? I thought metamask imposes some limits

**Comment by rahul-kothari** [comment]
Any update on changing the URL? More useful now that uniswap is on mainnet

**Comment by willhennessy** [comment]
Agreed, but we have a bunch of other tasks for L2 as well so we haven't had
a chance to start yet sorry!

**Comment by moodysalem** [comment]
> one unknown--what to do when the user is connected to a different network when they want to send the transaction? need to disable buttons everywhere, lots of edge cases

another complication is that we need to fetch some data from mainnet always (e.g. token list ens urls, logo ens urls), so switching the network connector chain id will be a little difficult without breaking those things. we may want a app network connector, an always-mainnet network connector, and the wallet network connector to be three separate providers
