### ISSUE TITLE
Support WETH to add liquidity to existing positions

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#1969]
Today it is not possible to add WETH to an existing LP position. You can only add ETH.

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/3705

**Comment by Rachel-Eichenberger** [comment]
While there is not an add weth switch for the LP position, there is a work around

It is possible to replace the **ETH** in the address bar with the WETH address **0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2**
this allows adding weth instead
