### ISSUE TITLE
Price sliders color on L2

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2049]
**Bug Description**
While connected to Optimism, on the Add Liquidity distribution chart, the color of the price sliders is wrong. For example on ETH/DAI both sliders are yellow (DAI colored)

<img width="901" alt="Screen Shot 2021-07-13 at 10 59 56 PM" src="https://user-images.githubusercontent.com/5455577/125554343-10a6369b-b164-4fe8-b606-57cd4bc745bf.png">

https://app.uniswap.org/#/add/ETH/0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1/500

**Comment by justindomingue** [comment]
Hardcoded to yellow on non-mainnet 😐 

https://github.com/Uniswap/uniswap-interface/blob/43cefbdc6aff3f7c98f6e25dee8a1cabb7c7e1c9/src/hooks/useColor.ts#L8-L11

**Comment by justindomingue** [comment]
I think vibrant is failing to download the image ```Error: Fail to load image: https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=010
    at HTMLImageElement.img.onerror (index.ts:86)```

**Comment by willhennessy** [comment]
done! cryptologos updated their policy.
