### ISSUE TITLE
imported tokens from lists should retain logo and list information

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/interface#2104]
**Bug Description**
when you import a token from a list we dont store the logo uri and so it's not shown

**Steps to Reproduce**

import a token from a list

**Expected Behavior**
logo from list shows

**Additional Context**

we may just want to store the imported token address instead of all the details in redux

**Comment by william-weber** [comment]
I'll do this one. 🙂

**Comment by moodysalem** [comment]
I just tested and could not reproduce, I think this issue is fixed
