### ISSUE TITLE
Unsupported older browser

### ISSUE THREAD

**Issue by circle-hotaru** [Uniswap/interface#2227]
**Bug Description**
I get a white page when I visit app.uniswap.org on Android 8's browser.

**Steps to Reproduce**

1. Go to app.uniswap.org on some older Androids (like Android 8)

**Expected Behavior**
Normal display

**Additional Context**
![Screenshot_1629427169](https://user-images.githubusercontent.com/48060080/130175906-576fa77e-2eff-434d-a9c9-309ea1590c85.png)

**Comment by willhennessy** [comment]
If Android version (or corresponding max supported browser version) is indeed the issue, then this is P1

Android 8 still have 9% market share
Android <=8 has 25% market share

https://gs.statcounter.com/os-version-market-share/android

**Comment by circle-hotaru** [comment]
If I update my browser this error does not happen. But the bug still occurs when I use imToken to access Uniswap, which is accessed using Android WebView. It looks like this bug is happening on Chinese phones because Chinese phone vendors restrict Android WebView updates.

**Comment by p0s** [comment]
To add numbers from imToken-side. We checked and estimate about 80% of our Uniswap users impacted since we do have a user base with lots of Chinese brand phones

**Comment by samlin425** [comment]
Hi @willhennessy , Nice to meet you. I'm the project manager of imToken. 
As you know, we have already fixed this issue, what's your plan of merge the PR?

**Comment by willhennessy** [comment]
I didn't realize you had a fix. I've assigned a reviewer, thanks!
