### ISSUE TITLE
Missing USD value & price impact on DOG token

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2292]
When swapping for the $DOG token, we don't show the USD output value or the price impact in the output swap box. This is an imported token not on any token list.

<img width="583" alt="Screen Shot 2021-09-03 at 6 41 52 PM" src="https://user-images.githubusercontent.com/5455577/132071922-625d077d-8105-4f3f-84f8-c075786e3bea.png">

Expected behavior:  both should appear, like e.g. DAI
<img width="577" alt="Screen Shot 2021-09-03 at 6 42 00 PM" src="https://user-images.githubusercontent.com/5455577/132071923-4618c8df-fc6c-406a-9429-e1f043e81c18.png">

The interface *is* computing price impact. You can see it on hover.
<img width="608" alt="Screen Shot 2021-09-03 at 6 43 38 PM" src="https://user-images.githubusercontent.com/5455577/132071924-4b70ca19-6188-43b2-b087-4c99b159aa85.png">

**Comment by justindomingue** [comment]
@tinaszheng we get the usdc price by executing a trade from DOG to 100_000$ USDC. My hunch is there isn't enough liquidity here and so that trade fails?

https://github.com/Uniswap/interface/blob/main/src/hooks/useUSDCPrice.ts#L22

**Comment by justindomingue** [comment]
Hm actually.. I think it should find a route through ETH (DOG -> ETH -> USDC)

There's 8mil TVL: https://info.uniswap.org/#/tokens/0xbaac2b4491727d78d2b78815144570b9f2fe8899

**Comment by tinaszheng** [comment]
also not sure if this is still an issue anymore! i see the price displayed in the app:
![image](https://user-images.githubusercontent.com/59578595/146135767-7ca30cc1-953f-4491-ac3a-dce64ff14ec3.png)

it does take a few seconds to load though, so maybe it was just due to the delay?

**Comment by justindomingue** [comment]
there may have been too little TVL at that point? Probably okay to close.
