### ISSUE TITLE
V2 SDK: getting optimal routes - useless hop iteration from 1 to maxHops

### ISSUE THREAD

**Issue by devengn** [Uniswap/interface#2296]
https://github.com/Uniswap/uniswap-interface/blob/627a5d3a98e65fae431fed3d650f6e359890e523/src/hooks/useV2Trade.ts#L53

In V2 SDK, to get optimized routes, why are we iterating every hop?
Only processing `maxHops` will get all possible results, I think.

**Comment by willpote** [comment]
The `isTradeBetter` function has a param `BETTER_TRADE_LESS_HOPS_THRESHOLD`. It means that a route with more hops must be better than a route with fewer hops by `BETTER_TRADE_LESS_HOPS_THRESHOLD` percent: https://github.com/Uniswap/uniswap-interface/blob/627a5d3a98e65fae431fed3d650f6e359890e523/src/hooks/useV2Trade.ts#L58

This is done as a rough way to consider gas when generating routes. i.e. more hops = more gas, so it isn't always desirable to pick the route with more hops.

There is repeated work being done for every call to `Trade.bestTradeExactIn`, so code could definitely be more efficient. PRs welcome.
