### ISSUE TITLE
Light mode approving text incorrect color

### ISSUE THREAD

**Issue by callil** [Uniswap/interface#2310]
<img width="529" alt="Screen Shot 2021-09-01 at 11 47 34 AM" src="https://user-images.githubusercontent.com/1355319/132397783-dc3334b2-44ce-44d5-9f54-9f97982c0efa.png">

**Comment by justindomingue** [comment]
do we have a consistent repro for this? I tried every state combination but could not get to this.

**Comment by justindomingue** [comment]
Will close. Please reopen if there a repro.
