### ISSUE TITLE
Fix broken images on Arbitrum token list

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2324]
half of the URLs in arbitrum token list fail to load.  They are all from zapper.fi. 

Most of the links when loaded in a browser, return a 404 on zapper.fi

But some like USDC actually do load the image, so I don't know why it doesn't load in our interface. https://zapper.fi/images/USDC-icon.png

<img width="568" alt="Screen Shot 2021-09-11 at 12 35 29 AM" src="https://user-images.githubusercontent.com/5455577/132936345-e283c09f-9646-4042-a1a2-8f9bf689c715.png">

**Comment by willhennessy** [comment]
hey jordan, checking in on this one! I suspect it's an issue on zapper's end, so would be good to give them a heads up as soon as we diagnose it

**Comment by JFrankfurt** [comment]
![image](https://user-images.githubusercontent.com/5773490/133690339-1dc196d1-5f57-4f76-8043-5bdd61df0cc2.png)

https://bridge.arbitrum.io/token-list-42161.json

@willhennessy it looks like arbitrum just isn't including images for these tokens

cc @DZGoldman

**Comment by willhennessy** [comment]
I don't think that's true of all tokens. For example USDC has an image URL but it doesn't render in the itnerface

```      {
         "logoURI":"https://zapper.fi/images/USDC-icon.png",
         "chainId":42161,
         "address":"0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8",
         "name":"USD Coin Arb1",
         "symbol":"USDC",
         "decimals":6,
         "extensions":{
            "l1Address":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
            "l1GatewayAddress":"0xcEe284F754E854890e311e3280b767F80797180d"
         }
      },
```

as for the others, @DZGoldman can you ack and fix on your end?

**Comment by JFrankfurt** [comment]
@willhennessy - that one does load for me: 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/5773490/134774037-d3e08463-84d1-47ea-8248-91b2458dccd4.png">
Are you getting any failed network requests for assets? They're all succeeding on my end.

**Comment by willhennessy** [comment]
yes sir I'm getting many 404 errors and very few images. screenshot attached

<img width="1435" alt="Screen Shot 2021-10-02 at 6 22 06 PM" src="https://user-images.githubusercontent.com/5455577/135733220-91b80ccd-9ce1-4f1f-878b-b9659a4502bf.png">

**Comment by willhennessy** [comment]
https://github.com/OffchainLabs/arb-token-lists/issues/3
