### ISSUE TITLE
Add Swahili language support

### ISSUE THREAD

**Issue by Sowiedu** [Uniswap/interface#2344]
**Is your feature request related to a problem? Please describe.**
Third-World countries who can benefit the most from decentralised applications often have a lack of english language skills. This could (at least in part) be solved by adding the Swahili language to the Uniswap UI (with a fallback to english)

**Describe the solution you'd like**
Add the Swahili language to the Uniswap UI

**Describe alternatives you've considered**
Using the english interface.

**Additional context**
I come from Germany and live in Tanzania right now and gathered some insight on the local payment culture, especially digital payments, long/short time horizons etc. and I think it is worth to add the Swahili language to dApps. Me (and people I know personally, Swahili native speakers) can help with the translation. I do not know where/how to start tho.

**Comment by justindomingue** [comment]
Thanks @Sowiedu . We can probably pick this up next week. A good place to start is to create an account on [Crowdin](https://crowdin.com/project/uniswap-interface/invite?d=b5854635o6g5p4g473g4g3f4b36333536303b353l443g4636313a3c3d4m4f4k4l4v2j4m4i4j4j4e49383f4b3p403n4o4u2m4d3f483833333630353h3g483k4v293835353d4o4k4f4o483e4n4i4i4n4l433a3r413t463h4p423g4d3l4237373c54393a3b3s483). Some (minimal) interface work will be required to initialize the new language, but after that you'll be able to contribute to translations on Crowdin.

@willhennessy let's also do Thai

**Comment by Sowiedu** [comment]
Hey @justindomingue thanks for taking care of this so quickly, already started it!

**Comment by Sowiedu** [comment]
Worthy to mention is also that there are quite some words in Swahili that stem from english words and sound similar and are written in a similar way. And some words that do not have a swahili pendant and the english one gets used instead. 

My suggestion would be to type in the english word as the translated word for these cases. Not sure where to mention this to avoid confusion when approving translations @justindomingue

**Comment by justindomingue** [comment]
@Sowiedu what should the name of the language be in the dropdown? e.g. https://github.com/Uniswap/uniswap-interface/blob/main/src/constants/locales.ts#L65

**Comment by Sowiedu** [comment]
@justindomingue It should be "Kiswahili". (Swahili is the "english name" of the language, Kiswahili is the local way)

**Comment by Sowiedu** [comment]
Please not for the locale it should be referred to as the tanzanian version of Swahili, not the kenyan one. @justindomingue

**Comment by justindomingue** [comment]
@Sowiedu I changed the locale in crowdin and copied over your translations. #2397

**Comment by Sowiedu** [comment]
@justindomingue Hi, I noticed that you removed me as a proof reader for the en-swtz on Crowdin. I just wanted to let you know that I still am active. I kindly ask to reinstate me on Crowdin.
