### ISSUE TITLE
Fix "Show closed positions" checkbox state saving behaviour on Arbitrum to be consistent with mainnet

### ISSUE THREAD

**Issue by Sowiedu** [Uniswap/interface#2356]
**Bug Description**
The state of the checkbox "Show closed positions" on the [positions overview page](https://app.uniswap.org/#/pool) saves the state of the checkbox on Arbitrum in an unexpected way which is inconsistent with behaviour of mainnet. On mainnet the state is saved for the user the moment the checkbox is interacted with. On Arbitrum the checkbox state seems to get saved only on page change.

**Steps to Reproduce**

1. Make sure you are a liquidity provider in any pool on UniswapV3 on Arbitrum and have at least one open and one closed position.
2. Go to https://app.uniswap.org/#/pool
3. Observe state of checkbox "Show closed position"
4. Change state of said checkbox
5. Refresh the page
6. Observe that state of checkbox got reset to state in Step 3
7. Change checkbox state again
8. This time don't refresh but click on "Swap" Menu item
9. Click on "Pool" Menu item to get back to the positions overview
10. Observe state of checkbox now is correctly set to the state set in Step 7.

**Expected Behavior**
I expect the state of the checkbox getting saved for the user the moment I change the state, not on leaving the page.

**Additional Context**
It may behave similar on Optimism, didn't test it.
Browser (latest as of writing this report): Brave Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)

**Comment by Sowiedu** [comment]
This seems to be not an issue when using IPFS.

**Comment by Jdecristi** [comment]
@JFrankfurt is this still a bug? is so what do you think is the best route? LocalStorage? SessionStorage?

**Comment by JFrankfurt** [comment]
@Jdecristi I just clicked around a bit and it looks like we've got a consistent behavior across all networks now. None appear to save the user's preference for showing networks. Refreshing or navigating away will clear the "show closed positions" selection.

**Comment by Jdecristi** [comment]
@JFrankfurt, can I go ahead and take it then? I have a solution

**Comment by JFrankfurt** [comment]
go for it!
