### ISSUE TITLE
Don't overwrite local storage token list data with error responses

### ISSUE THREAD

**Issue by JFrankfurt** [Uniswap/interface#2368]
Currently we will clear the user's stored token list data and replace it with an error state if the request fails. This is annoying if the list is unreachable or the user is offline, since the data is still valid and shouldn't be discarded.

**Comment by JFrankfurt** [comment]
https://github.com/Uniswap/interface/blob/main/src/state/lists/reducer.ts#L91-L103

**Comment by JFrankfurt** [comment]
Sweet, do it bruv. 👏👏

**Comment by Jds-23** [comment]
@JFrankfurt can you provide me test cases to reproduce this?

**Comment by Jds-23** [comment]
@JFrankfurt do you have them it would help?😁

**Comment by JFrankfurt** [comment]
You should be able to repro this issue by loading the site, killing your
network connection, and reloading. The list data will load the first time,
then be replaced with errors when you're unable to complete the requests
while offline.

**Comment by Jds-23** [comment]
@JFrankfurt let me know if it works? 😁

**Comment by JFrankfurt** [comment]
@Jds-23 Can you make a PR? I'll approve the test deployment.
