### ISSUE TITLE
Package scripts are not compatible with Windows

### ISSUE THREAD

**Issue by pengchew** [Uniswap/interface#2442]
**Bug Description**
./src/constants/locales.ts
Module not found: Can't resolve '../locales/en-US' in 'C:\Programming\interface\src\constants'

**Steps to Reproduce**

1. yarn install && yarn start

**Comment by pengchew** [comment]
<img width="960" alt="1" src="https://user-images.githubusercontent.com/64325702/134804620-f026ca91-e35a-401d-bc8e-33c9e04b7b4a.png">

**Comment by justindomingue** [comment]
`touch locales/en-US` should do it.

cc @zzmp

**Comment by zzmp** [comment]
Thanks for including the terminal output. It looks like contract compilation failed in postinstall, so i18n compilation never occurred. I'll double check the scripts today to see what causes this.

**Comment by zzmp** [comment]
@pengchew this occurred because our package scripts were not written to support windows, and `./node_modules/@uniswap/?(v3-core|v3-periphery)/artifacts/contracts/**/*.json` is not a valid shell expansion for you. It will need to be split up to separate commands to be more compatible.

**Comment by pengchew** [comment]
> @pengchew this occurred because our package scripts were not written to support windows, and `./node_modules/@uniswap/?(v3-core|v3-periphery)/artifacts/contracts/**/*.json` is not a valid shell expansion for you. It will need to be split up to separate commands to be more compatible.

Thanks for the explanations, got it.

**Comment by meiskam** [comment]
`touch` also doesn't exist on windows .. add `touch-for-windows` package maybe?

**Comment by Thorhus** [comment]
> for windows update scripts section of package.json to this and run with yarn install
> 
> ```
> "scripts": {
>     "contracts:compile:abi": "typechain --target ethers-v5 --out-dir src/abis/types ./src/abis/**/*.json",
>     "contracts:compile:v3": "typechain --target ethers-v5 --out-dir src/types/v3 ./node_modules/@uniswap/v3-core/artifacts/contracts/**/*.json && typechain --target ethers-v5 --out-dir src/types/v3 ./node_modules/@uniswap/v3-periphery/artifacts/contracts/**/*.json",
>     "contracts:compile": "yarn contracts:compile:abi && yarn contracts:compile:v3",
>     "graphql:generate": "graphql-codegen --config codegen.yml",
>     "prei18n:extract": "touch src/locales/en-US.po",
>     "i18n:extract": "lingui extract --locale en-US",
>     "i18n:compile": "yarn i18n:extract && lingui compile",
>     "postinstall": "yarn contracts:compile && yarn graphql:generate && yarn i18n:compile",
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test --env=./custom-test-env.js",
>     "test:e2e": "start-server-and-test 'serve build -l 3000' http://localhost:3000 'cypress run --record'",
>     "bundle": "microbundle --tsconfig tsconfig.lib.json src/lib/index.tsx --format esm,cjs",
>     "cosmos": "open http://localhost:5000 && cross-env FAST_REFRESH=false cosmos"
>   },
> ```

Unfortunately, that issue is not solved on windows yet.
Is there any solution?

**Comment by shopglobal** [comment]
> for windows update scripts section of package.json to this and run with yarn install
> 
> ```
> "scripts": {
>     "contracts:compile:abi": "typechain --target ethers-v5 --out-dir src/abis/types ./src/abis/**/*.json",
>     "contracts:compile:v3": "typechain --target ethers-v5 --out-dir src/types/v3 ./node_modules/@uniswap/v3-core/artifacts/contracts/**/*.json && typechain --target ethers-v5 --out-dir src/types/v3 ./node_modules/@uniswap/v3-periphery/artifacts/contracts/**/*.json",
>     "contracts:compile": "yarn contracts:compile:abi && yarn contracts:compile:v3",
>     "graphql:generate": "graphql-codegen --config codegen.yml",
>     "prei18n:extract": "touch src/locales/en-US.po",
>     "i18n:extract": "lingui extract --locale en-US",
>     "i18n:compile": "yarn i18n:extract && lingui compile",
>     "postinstall": "yarn contracts:compile && yarn graphql:generate && yarn i18n:compile",
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test --env=./custom-test-env.js",
>     "test:e2e": "start-server-and-test 'serve build -l 3000' http://localhost:3000 'cypress run --record'",
>     "bundle": "microbundle --tsconfig tsconfig.lib.json src/lib/index.tsx --format esm,cjs",
>     "cosmos": "open http://localhost:5000 && cross-env FAST_REFRESH=false cosmos"
>   },
> ```

can confirm

**Comment by nameishua** [comment]
windows Solution ： "echo test"  replace "touch"
