### ISSUE TITLE
Coin.io uniswap link bug

### ISSUE THREAD

**Issue by JT202064** [Uniswap/interface#2448]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**

1. Go to ...coin.io
2. Click on ...verify wallet address
   ...manage uniswap pool through coin.io geomining site through dapp browser

**Expected Behavior**
Clear path to manage my v3 uniswap position

**Comment by justindomingue** [comment]
Note related the interface AFAICT.
