### ISSUE TITLE
UniswapV2 Add Liquidity: Invalid Pair

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/interface#2469]
**Bug Description**
UniswapV2 Add Liquidity hides second token input and shows "Invalid pair".

<img width="492" alt="Screen Shot 2021-09-28 at 7 41 31 PM" src="https://user-images.githubusercontent.com/799573/135194376-5787681c-f1dd-4374-9e28-5c4bf61775aa.png">

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/add/v2/ETH

**Expected Behavior**
I can add liquidity to uniswapv2 on Görli.

**Additional Context**
I am on Görli. I have imported many coins there.
The dropdown for the first token input seems to work fine but doesn't fix the second input.

**Comment by wjmelements** [comment]
Could be a CSS issue; the element seems to be there.
<img width="336" alt="Screen Shot 2021-09-28 at 7 50 00 PM" src="https://user-images.githubusercontent.com/799573/135194847-28aadcab-e7fa-49fc-9a9e-af14f465bc77.png">

**Comment by wjmelements** [comment]
I also see the issue after refreshing on mainnet.

**Comment by moodysalem** [comment]
Thanks for reporting, being tracked here https://github.com/Uniswap/interface/issues/2470
