### ISSUE TITLE
Browser not loading token1 in add liquidity V2

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#2470]
**Bug Description**

Seems specific to chrome browser.
when trying to add Liquidity in V2 token one doesn't have a token selection button

has been seen in v3, but not currently seeing

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/add/v2/ETH

**Expected Behavior**
Should show both Token selection buttons.

**Additional Context**

currently working around this by selecting token 0 which gives a bad link 
like
https://app.uniswap.org/#/add/v2/0x3d6F0DEa3AC3C607B3998e6Ce14b6350721752d9/undefined
then having user change the undefined to eth
seems like it is breaking on loading token1 selection box
However haven't seen a console error related to it.

![image](https://user-images.githubusercontent.com/60412342/135194777-92a8da47-1a36-40c6-84da-07f0aaf54ea2.png)

**Comment by moodysalem** [comment]
looks like the same issue that was fixed yesterday
