### ISSUE TITLE
DAI is missing from Arbitrum token list

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2490]
DAI is in Arbitrum's token list:  https://bridge.arbitrum.io/token-list-42161.json

And it appears in the common bases field

But it is not in the scrollable token list , and searching for 'DAI' in the text field yields no results.

<img width="558" alt="Screen Shot 2021-10-03 at 10 00 52 PM" src="https://user-images.githubusercontent.com/5455577/135783130-6ee48f40-244c-490d-abf0-72e4a6dbf2e2.png">

**Comment by moodysalem** [comment]
arbitrum updated their list

created https://github.com/Uniswap/token-lists/issues/71 to track removing version
