### ISSUE TITLE
Adter update Uniswap doesn;t detect network which Wallet Connect is used

### ISSUE THREAD

**Issue by MikaelLazarev** [Uniswap/interface#2515]
**Bug Description**
I connect my app with Uniswap using wallet connect. App is used Kovan network, however, Uniswap still stay on Mainnet,

**Steps to Reproduce**

1. Go to Wallet
2. Click on Connect Wallet Connect
3. Conntec to app on Kovan

**Expected Behavior**
Uniswap will switch to Kovan, but it's still on Mainnet :(

**Additional Context**
It worked perfect a few days ago, I didn;t my codebase, however, not it works incorrect.

Please, help!

**Comment by willhennessy** [comment]
jordan, perhaps related to our recent network selector changes?

**Comment by willhennessy** [comment]
hi mikael, are you still having this issue? if so, please re-open and share some detail. I don't understand this part "Uniswap will switch to Kovan, but it's still on Mainnet"

**Comment by MGCEXNZ** [comment]
when connect to uniswap , and swap token ,error message occur as attached
![image](https://user-images.githubusercontent.com/41608204/145061497-f46fcdfb-9991-4022-96c9-064958584640.png)
