### ISSUE TITLE
show usdc price in add liquidity below upper and lower price tickers

### ISSUE THREAD

**Issue by justindomingue** [Uniswap/interface#2519]
example:
1 ETH = 3402 DAI ($3401.63)

**Comment by willhennessy** [comment]
Thanks prakash!  Here is a design spec from our UX designer. We recommend putting the USD value in parentheses on the same line as the token price, just above the bar chart.

<img width="759" alt="Screen Shot 2021-10-15 at 3 08 19 PM" src="https://user-images.githubusercontent.com/5455577/137781169-697d7488-b4ce-41f2-9564-99157af48767.png">

**Comment by justindomingue** [comment]
decision is to show dollar price for ETH and when either token is a stable coin (we do not have a strong list rn, so can probably just do for DAI,USDC,USDT?)

**Comment by tinaszheng** [comment]
@willhennessy @justindomingue it looks like the USD price we're displaying is for the base currency - so for a ETH-DAI pairing we are displaying the USD value of DAI (is this understanding correct?) 

It seems like from the copy, e.g. "3820.76 DAI per ETH ($3,900)" it's suggesting that is the ETH price? Thoughts on changing it to something like "3820.76 DAI ($3,900) per ETH"?

**Comment by callil** [comment]
I had the same idea @tinaszheng! maybe we can see it in practice and review it.

**Comment by tinaszheng** [comment]
@callil yea! here are the two side by side for comparison :D i guess either looks fine imo, as the savvy user can probably figure out what's going on (famous last words tho)

![Screen Shot 2021-12-15 at 2 28 51 PM](https://user-images.githubusercontent.com/59578595/146274827-2a123b6a-2d84-42ad-9b13-091db649508a.png)
![Screen Shot 2021-12-15 at 2 29 36 PM](https://user-images.githubusercontent.com/59578595/146274840-a0d31f50-8b2d-42ee-bb99-e4338808263c.png)
