### ISSUE TITLE
Bug: Token USD-price on UI is 10× of actual shown on v2.info.uniswap

### ISSUE THREAD

**Issue by uniyj** [Uniswap/interface#2523]
**Bug Description**
NGC token (v2-only pools) USD-price on UI is ≈10× of what's shown in v2.info.uniswap.org.

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/swap
2. Choose to swap from NGC (`0x72dD4b6bd852A3AA172Be4d6C5a6dbEc588cf131`) to USDT
3. UI will show NGC's USD price as ≈10× of actual price, e.g. UI shows $3.46 when actual (also shown on [v2.info.uniswap.org](https://v2.info.uniswap.org/pair/0x5e4a92625a337707ba362abff463bccc5b896d21)) is $0.346.

**Expected Behavior**
UI should show correct USD-price consistent with v2.info.uniswap.org.

**Additional Context**
NGC only has liquidity in v2, and the 10× USD-price estimate shows up no matter what options I tried: Auto Router on/off, force V2 (`use=V2`), force V3 (`use=V3`), swap vs Eth/USDT/USDC/DAI...

UI screenshot:
![image](https://user-images.githubusercontent.com/84749041/136750432-ccdc0b16-41fd-4e4d-a70a-6ef9a9ae6d60.png)

v2.info.uniswap.org screenshot:
![image](https://user-images.githubusercontent.com/84749041/136750630-34db61cd-4b71-4982-892f-86923de20a1c.png)

**Comment by kAited93** [comment]
same problem applies for selling. User has 406.7 coins but when trying to sell on uniswap, only showing 40.67 coins (10x less) and selling at 10x the price. 

![image](https://user-images.githubusercontent.com/92311807/136790367-5e2e91d1-e4f3-4b53-aa74-a58db7817a64.png)

![image](https://user-images.githubusercontent.com/92311807/136790400-c5ee2673-1dd3-4245-8d7d-22e13ac4af0e.png)
