### ISSUE TITLE
Uniswap interface not working on coinbase wallet

### ISSUE THREAD

**Issue by Cryptomotion1** [Uniswap/interface#2527]
Hello, when I want to swap my token using dabb on my coinbase wallet the page is blank. I have re-set my phone settings, cleared cache but it does'nt work. I have also tried on my desktop and it's not working.  Could you please fix this I am losing money from trading. https://app.uniswap.org/

**Comment by willhennessy** [comment]
Hi cryptomotion1, sorry to hear that. I'm not able to reproduce the issue. 

You tried this on your desktop computer and app.uniswap.org will not load either? What error code do you see?
