### ISSUE TITLE
Unable to approve spending of wBTC on UniSync

### ISSUE THREAD

**Issue by sanchopansa** [Uniswap/interface#2559]
**Bug Description**
Submitting a transaction for approving the spending of wBTC fails

**Steps to Reproduce**

1. Go to https://uni.zksync.io/#/swap
2. Select wBTC as input currency
3. Select any other currency as the output
4. Submit & sign the tx
5. The tx fails

**Expected Behavior**
wBTC should be approved for spending

**Additional Context**
I've been able to approve all other coins (DAI, USDC, LINK) for spending. The above is 100% reproducible for me, here are 3 txs that are shown as failed in the UI (and also have no info in the explorer):

- https://zksync2-alpha.zkscan.io/transactions/0xebd4654b58abcfbdf92f77340d4243e40fefda2491253c5ef57f205b7f5dcf7e
- https://zksync2-alpha.zkscan.io/transactions/0xe3298d8040fd9803ae7bc62791fb24aa316cc5ae021604311b3c0e5b72dab11e
- https://zksync2-alpha.zkscan.io/transactions/0x39ad11d729ac1c797519b2f8189d50c63f2e0d90b3399c3187a49da98b50a6ab

Here are a couple of successful txs for approving other coins:

- https://zksync2-alpha.zkscan.io/transactions/0x77dfff6e2f5adbbe770df4148e76bdd6afdcd80eb9cf5c0a4fec4918642bd18d
- https://zksync2-alpha.zkscan.io/transactions/0x0ebf7afea0fbfe310e9f847e1bc1d297b44b668621238f7a40adcd2ff5399f6d

**Comment by willhennessy** [comment]
Hi sanchopansa!  uni.zksync.io is a fork of the uniswap protocol and interface. It's run by a different team so we aren't able to help with your issue. Sorry about that, wish you well.
