### ISSUE TITLE
Extra padding below auto fee tier

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2606]
When a fee tier is auto selected, there is an extra white space below the "82% select" badge

<img width="1197" alt="Screen Shot 2021-10-13 at 1 47 25 PM" src="https://user-images.githubusercontent.com/5455577/137186013-d200ffe0-a211-4426-96b6-a70b90161ede.png">

**Comment by micaelr95** [comment]
@willhennessy I would say that this CORS error is related to issue #2049 and not directly related to this issue.

What browser are you using? What is your screen resolution? Are you using any type of adblock?
