### ISSUE TITLE
Some tokens not showing up properly from Token List 

### ISSUE THREAD

**Issue by admazzola** [Uniswap/interface#2653]
**Bug Description**
When I am on uniswap.org with network set to Optimism Mainnet, I have this list turned ON:

https://tokenlists.org/token-list?url=https://static.optimism.io/optimism.tokenlist.json

You will notice that 0xBitcoin is one token in this list.

However, that token does not show up in the dropdown at all in the Uniswap Interface.  So the token is in the list I have selected but is not appearing in the dropdown.  

**Steps to Reproduce**

1. Go to uniswap.io with network set to Optimism Mainnet
2. Make sure the 'Optimism List' is turned on [also go into Manage Lists and click the gear -> 'View List' for that list and you will see 0xbitcoin in the list json]
3. try to select an asset  to swap into and realize that 0xbitcoin is not there 

**Expected Behavior**
0xbitcoin should be in the dropdown

**Comment by willhennessy** [comment]
0xbtc and RAI appear now
