### ISSUE TITLE
Lost/stolen ether

### ISSUE THREAD

**Issue by Happyguy65** [Uniswap/interface#2712]
I have done a couple of transactions so far and either I have not recieved the coins or the transaction fails yet I've been charged for each transaction even if it fails the ethererum is still taken from my acc I need to know if that is a thing or if I can get that back

**Comment by Happyguy65** [comment]
So found out it is the gas price but even if they have went through I haven't recieved my coin

**Comment by Drama99** [comment]
Hi The same happends to me. I was trying to buy safemoon I I by uniswap in trust wallet. I did buy but it’s not showing in my trust wallet

**Comment by willhennessy** [comment]
Hello. Happyguy, yes the ethereum network miners charge you gas fees even for a failed transaction because they need to do work to compute the failure.

Drama, please talk to Trust Wallet about that issue.
