### ISSUE TITLE
Increase liquidity form off center

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2741]
**Bug Description**
The increase liquidity form on Optimism (and probably arbitrum) is left aligned. I suspect this is due to the top banner that we added above the form.

![Uniswap-Interface](https://user-images.githubusercontent.com/5455577/140333781-9f1598cb-53a2-46a2-a389-87314085ba43.png)

**Steps to Reproduce**

1. Go to an active liquidity position
2. Click increase liquidity

i.e. app.uniswap.org/#/increase/ETH/0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4/3000/64731

the entire add liquidity form box should be centered on the page

**Comment by bkrochta** [comment]
I can work on this issue

**Comment by willhennessy** [comment]
Thanks Ben!
