### ISSUE TITLE
180 minutes artificial front-end limitation - allow user to set any number 

### ISSUE THREAD

**Issue by marsrobertson** [Uniswap/interface#2754]
Basically I have some small amount of a token.

180 minutes (3 hours) might be not enough...

![image](https://user-images.githubusercontent.com/44369284/140668338-1f722292-26f5-4b2a-b510-71e2444e7f23.png)

...I just want to set slippage to some large % and enough deadline.

Of course I could use Etherscan and write to the contract directly but I just prefer no artificial limits on the front-end.

**Comment by NoahZinsmeister** [comment]
closing in favor of #2744
