### ISSUE TITLE
Display Uniswap token list in UI

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2756]
the Uniswap Labs default token list should be a visible option in the token list menu

* logo: brand
* name: Uniswap Labs Token List
* state: on by default
* Gemini token list should continue to be on by default as well

**Comment by bkrochta** [comment]
@willhennessy should the Uniswap Token List be the only list that is on by default or should the Gemini Token List remain on by default as well?

**Comment by Jds-23** [comment]
@willhennessy should I take this up?

**Comment by willhennessy** [comment]
thank you both! Yes the Gemini token list should also remain on by default.

You're both welcome to work on this! A few things to know
* the Uniswap token list is currently pulled into the app at build time via import [here](https://github.com/Uniswap/uniswap-interface/blob/d18974480a1033e84c67d4122c8c926ee14682bd/src/state/lists/hooks.ts#L119).  We should probably change this to load the list at runtime just like all the other token lists from the source: https://gateway.ipfs.io/ipns/tokens.uniswap.org

@moodysalem anything else to add?

**Comment by Jds-23** [comment]
Will take this up this weekend.
