### ISSUE TITLE
Compile Error: "Module not found: Can't resolve '../locales/en-US'"

### ISSUE THREAD

**Issue by coolerwind** [Uniswap/interface#2784]
I have got the **Uniswap Release v4.22.2** project source code from the IPFS link and tried to run project on my local.
After installing all dependencies using 'yarn' and 'running yarn start', I got "Module not found: Can't resolve '../locales/en-US' in my directory".
How can I fix this error?

Source code: https://github.com/Uniswap/interface/releases
![Error](https://user-images.githubusercontent.com/75097898/141526588-361e9240-9d6a-4cf2-8dc9-6d726f8ff88e.png)

**Comment by akhilchhetri** [comment]
I got the same issue, How did you solved this ??

**Comment by johansten** [comment]
Samesies
