### ISSUE TITLE
Failed to load schema from subgraph

### ISSUE THREAD

**Issue by rahulbhadja** [Uniswap/interface#2789]
**Bug Description**
on yarn start, it is not running locally and throwing errors like this,
 Failed to load schema from https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3:

**Steps to Reproduce**

1. Clone this repo
2. yarn install
3. yarn start
   ...

**Expected Behavior**
should run locally on localhost after genereting schema

**Additional Context**
It was running perfectly before today. But today i tried to run locally and it is giving an error of graphql-codegen. i tried cloning again but did not work.
Any help would be appreciated.

**Comment by afrazs** [comment]
Having the same issue. And there is no way to load schema alternatively?

**Comment by rahulbhadja** [comment]
@afrazs I don't know, I am still getting this issue and didn't find any solution.

**Comment by rahulbhadja** [comment]
@afrazs I don't know, I am still getting this issue and didn't find any solution.

**Comment by ngthtung** [comment]
I have same issue

**Comment by willhennessy** [comment]
are you still experiencing the issue? Ian just fixed the subgraph yesterday after the 0.01% fee tier launch

**Comment by rahulbhadja** [comment]
@willhennessy  yes, it is working now , thank you
