### ISSUE TITLE
Load ENS NFT profile picture

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2792]
ENS recently launched support for NFT profile pictures: https://medium.com/the-ethereum-name-service/step-by-step-guide-to-setting-an-nft-as-your-ens-profile-avatar-3562d39567fc

if the connected wallet has set one, we should load it as the user's avatar image in the app.

**Comment by justindomingue** [comment]
this should already work through davatar? You can test on rinkeby
