### ISSUE TITLE
Crash report: `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by Baronak** [Uniswap/interface#2801]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=light&exactAmount=698.9055&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "698.9055",
  "recipient": null
}
```

## Error

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## Stacktrace

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getCachedUrl (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:986470)
    at https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:987399
    at Fs (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1406388)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1424167)
    at Gi (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1346707)
    at Rs (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1405849)
    at https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1405760
    at L (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1423226)
    at MessagePort.k.port1.onmessage (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1421948)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Baronak** [comment]
![Schermafbeelding 2021-11-15 193450](https://user-images.githubusercontent.com/94325772/141835765-c1c5c214-41f0-4234-beb1-9c484c1540a0.png)

**Comment by Baronak** [comment]
![Schermafbeelding 2021-11-15 193556](https://user-images.githubusercontent.com/94325772/141835920-4f3d298a-5f84-477a-a36d-de603cfb4c55.png)

I can not make a offer?

**Comment by zzmp** [comment]
@Baronak can you include steps to reproduce this error? Were you using another application that used Uniswap as a widget?

**Comment by Baronak** [comment]
> @Baronak can you include steps to reproduce this error? Were you using another application that used Uniswap as a widget?

I use metamask on google ghrome

**Comment by zzmp** [comment]
Were you using opensea.io? If so, can you let me know the steps that you used to get to the failur?

**Comment by Baronak** [comment]
> Were you using opensea.io? If so, can you let me know the steps that you used to get to the failur?

I'm from the Netherlands. the first step. I want to make a offer. when i press make offer, this will appear on my screen

![Schermafbeelding 2021-11-15 193450](https://user-images.githubusercontent.com/94325772/141839502-7308bc35-62c7-4145-9fce-332095ff2fa1.png)

**Comment by zzmp** [comment]
t.getCachedUrl is called by @davatar/react/dist/Image.js.

**Comment by Baronak** [comment]
> t.getCachedUrl is called by @davatar/react/dist/Image.js.

What do I need to do whit that?

**Comment by zzmp** [comment]
Sorry - that's just a note to track the root source of this issue. I'm working on a resolution now. Thanks for your report!
