### ISSUE TITLE
Whitepaper missing from uniswap.org

### ISSUE THREAD

**Issue by jab416171** [Uniswap/interface#2819]
**Bug Description**
Whitepaper missing from uniswap.org

**Steps to Reproduce**

1. Go to [v3 whitepaper](https://uniswap.org/whitepaper-v3.pdf) or [v2 whitepaper](https://uniswap.org/whitepaper.pdf)
2. Notice that it's a 404

**Expected Behavior**
whitepaper should exist on uniswap.org

**Additional Context**
for temporary workaround you can view a cached version [here](https://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Funiswap.org%2Fwhitepaper-v3.pdf&oq=cache%3Ahttps%3A%2F%2Funiswap.org%2Fwhitepaper-v3.pdf)

**Comment by zzmp** [comment]
Both of these links resolved for me. Can you try again?

Also, where do you see the links on the uniswap.org page? I found the "V3 Whitepaper" link, but do not see one on the landing page for V2.

**Comment by jab416171** [comment]
Interesting, they're resolving now
