### ISSUE TITLE
should check forward resolution matches of ENS name set in the reverse ENS record

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/interface#2838]
**Bug Description**
if you set a reverse ENS record to a name, such as abc.eth, and do not control abc.eth, the app will show abc.eth as if that is your ENS name

**Expected Behavior**
we should also check the forward resolution matches the current wallet address before showing the ens name or other ens attributes in the header

**Comment by moodysalem** [comment]
@zzmp you may be interested in this context

**Comment by uniyj** [comment]
Hi @moodysalem, @zzmp. I think there might be a few other problems related to ENS, as reported by a number of tickets on Uniswap Discord.

A total of three tickets mentioned their addresses showing up as `0x000...` on Uniswap UI:
- Two of them seem to have multiple ENS names (including 'subdomain' names) resolving to their addresses.
- The third one does not seem to have any ENS reverse name set, but had a tx to ENS Reverse Registrar calling `setName` function with input variable string `0x000...`

I don't know if the above observations were indeed the reason(s) that they get addresses showing up as `0x000...` on the UI, more a guess from my part. I can provide more details (including links to the Discord tickets channels and their addresses) in DMs, just let me know what you need. Thanks.

**Comment by uniyj** [comment]
This is now resolved by PR 3040. Please close. Thanks.
