### ISSUE TITLE
Various Positions not showing dollar value on pool page 

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#2840]
**Bug Description**
Had a user report not being able to see Liquidity position value or fee value on pool page. Upon looking into it I noticed multiple other positions near it not showing as well.

I checked a bunch, seemed like something to do with the area (id#) of the position # ¯\ (◉‿◉) /¯
like 157300 was fine, but 157301 wouldn't show. Some in between there and 157306, show while others don't, I checked similar lower and higher numbers (not always open so couldn't see all) and was like a crap shot, some would show some wouldn't.

No console errors, so i'm not sure why some would show and some wouldn't

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/pool/157307 , https://app.uniswap.org/#/pool/157306 , https://app.uniswap.org/#/pool/157302
2. you'll see no values ( chrome and firefox tested)

**Expected Behavior**
To see the value of the LQ and fees

**Additional Context**
![image](https://user-images.githubusercontent.com/60412342/143287371-68d88c1a-fc4f-4487-a151-10d07b50ffaa.png)

![image](https://user-images.githubusercontent.com/60412342/143288292-c9758702-ff76-45a8-9ef7-e4b3220c9f1c.png)

![image](https://user-images.githubusercontent.com/60412342/143288570-79d09136-5dcb-46e6-9fb2-703fab4b27a6.png)

**Comment by moodysalem** [comment]
The reason is that we cannot find a reliable dollar price for one of the 2 tokens

The logic is here
https://github.com/Uniswap/interface/blob/f7ecdc4332a3bb2cbd21c14718bba79ff66361f6/src/hooks/useUSDCPrice.ts#L22

For mainnet, we must be able to find a route to buy 100k USDC with the token

**Comment by Rachel-Eichenberger** [comment]
Excellent thank you for the clarification :)
