### ISSUE TITLE
If trade details are entered and I connect wallet, we should stay on same network

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#2990]
Steps:
0. switch your metamask to Optimistic Ethereum or Arbitrum
1. visit app.uniswap.org with no wallet connected
2. enter trade details so you can check the price and route
3. decide you want to trade, so click 'Connect Wallet'

Actual behavior:  when the wallet connects, the app switches to your metamask network (OE) and completely drops all your input trade information (amounts, tokens, etc). You have to start over.

Expected behavior:  the wallet should switch to the network on which you were getting a quote. The app should trigger a metamask prompt to switch to that network.

note:  currently the unconnected wallet state is only and always on L1. So we just need to prompt to switch to L1.

Related: it will be nice to let people choose their network in the unconnected state https://github.com/Uniswap/interface/issues/2626

**Comment by Jds-23** [comment]
Hey @willhennessy i have time, I would like to take this up.

**Comment by willhennessy** [comment]
Great! We already have code to request the connected wallet to switch networks, so you can take a peek at that. That code is used when selecting a network from the network selector.

I think the tricky part will be managing app state in between the moment a wallet connects, and the moment the user accepts the prompt to switch networks. Because in between those two moments the wallet is connected to a different network

**Comment by willhennessy** [comment]
This was resolved by Moody's PR to Polygon + for network switching even when wallet is not connected
