### ISSUE TITLE
Chain specific (agnostic) URL

### ISSUE THREAD

**Issue by leandercapuozzo** [Uniswap/interface#3032]
Would improve user experience if LP positions were viewable at URLs which were agnostic to current chain (network) which my wallet is set to. If I am set Polygon https://app.uniswap.org/#/pool/129 views one pool, while when set to Ethereum it views another. 

A potential work around would be to add a further divide to the URL

/pool **/polygon** /129

**Comment by willhennessy** [comment]
in progress! thanks leander. going to close this since we're tracking it in https://github.com/Uniswap/interface/issues/1893
