### ISSUE TITLE
An error has poppd up

### ISSUE THREAD

**Issue by BigsteppA1** [Uniswap/interface#3054]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by tinaszheng** [comment]
hey @BigsteppA1! would you mind adding any information to the issue? otherwise ill go ahead and close this. thanks!

**Comment by BigsteppA1** [comment]
Ok
