### ISSUE TITLE
Clear currency input component when invalid currency address is in url parameters

### ISSUE THREAD

**Issue by tinaszheng** [Uniswap/interface#3056]
**Bug Description**
When users add an invalid token address to the url params, the "select a token" option disappears. This also happens when you import a token that exists on one chain (e.g. $BSTICK on Polygon), but does not appear on another, and you switch your network in the app later.

![image](https://user-images.githubusercontent.com/59578595/147709572-0ce0b130-8a64-40a8-b80b-d127d086fed1.png)

**Steps to Reproduce**

Either:
1. Set your wallet network to ETH
2. Go to https://app.uniswap.org/#/swap?inputCurrency=0x8e915a77e301ad12ad1f62012734cf7557eee81a

- or -
1. Set your wallet network to Polygon (correct network for $BSTICK)
2. Go to https://app.uniswap.org/#/swap?inputCurrency=0x8e915a77e301ad12ad1f62012734cf7557eee81a
3. Switch network to Ethereum

**Expected Behavior**
The token selector should be in its default state when the token address is invalid

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by skv-headless** [comment]
Hello. I would like to work on this issue. I see 2 possible solutions here:
1) suggested by @tinaszheng `The token selector should be in its default state`
2) or we can redirect to 404 page. That explicitly would tell that there is an issue with the link
