### ISSUE TITLE
Token DRC 0xa150db9b1fa65b44799d4dd949d922c0a33ee606 doesn't load price

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#3060]
**Bug Description**
Token DRC 0xa150Db9b1Fa65b44799d4dD949D922c0a33Ee606 locks trying to load price on new UI (works in old version IPFS links)

Token errors trying to call the 0.05% pool which does not have a pool
https://info.uniswap.org/#/tokens/0xa150db9b1fa65b44799d4dd949d922c0a33ee606

**Steps to Reproduce**

1. Go to app.uniswap.ort
2. load token DRC 0xa150Db9b1Fa65b44799d4dD949D922c0a33Ee606 and try swap
3. Console gives exactIn and exactOut fails to the .05% pool
   ...

**Expected Behavior**
loads price for swap

**Additional Context**
![image](https://user-images.githubusercontent.com/60412342/147771149-a8a53330-48df-4ad9-b391-718a6ee4d0c0.png)

**Comment by digitalreserve** [comment]
Please prioritize and fix this issue as soon as possible, as users cannot currently swap ETH for DRC (0xa150db9b1fa65b44799d4dd949d922c0a33ee606) on Uniswap V2.

**Comment by willhennessy** [comment]
@justindomingue wdyt?

**Comment by justindomingue** [comment]
@willpote will take a look.

**Comment by justindomingue** [comment]
interestingly, i can get routes through ETH but not ending in ETH

<img width="369" alt="Screen Shot 2022-01-10 at 2 21 05 PM" src="https://user-images.githubusercontent.com/1284993/148826045-bc905b93-8ee3-473a-841a-d0d5010dd3ac.png">

**Comment by willpote** [comment]
SDK is throwing 

Error: Invariant failed: DECIMALS

DRC token has decimals of 0 which is probably causing problems somewhere. Looking

**Comment by willpote** [comment]
This has been fixed in the API. Need to merge https://github.com/Uniswap/interface/issues/3060 to fix the client side router.
