### ISSUE TITLE
cant connect my coinbase wallet even though I put it on the right network Polygon 

### ISSUE THREAD

**Issue by Avi1977** [Uniswap/interface#3092]
I launch the app then I put it on the Polygon network then I choose coinbase wallet when I do that I get this message: Wrong Network Please connect to the appropriate Ethereum network.  my phone wallet is set to the polygon network so I'm not sure why it's asking me to conecct to the ethereum network?  

I would like to be able to scan the bar code with my phone so I can see the balance of my investment I put in money in a USD/Matic, LELX.io, Uniswap V2 

Thank you

![IMG_1267](https://user-images.githubusercontent.com/97538641/148985873-ac890ac3-5d0e-4077-822e-690e6d23b0b9.jpg)
![IMG_1269 (1)](https://user-images.githubusercontent.com/97538641/148985902-58cdc509-3aa5-4f9d-ada2-5e9a05dbe8bc.jpg)
![IMG_1270 (1)](https://user-images.githubusercontent.com/97538641/148985918-94dcb356-d375-418f-a82a-f256be7f35a2.jpg)

**Comment by willhennessy** [comment]
@JFrankfurt I believe the PR fixed this, can we mark closed?

**Comment by JFrankfurt** [comment]
Yes, this is fixed.
