### ISSUE TITLE
upgrade from web3-react v6

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/interface#3099]
This will come with a variety of usage and perf improvements

**Comment by willhennessy** [comment]
is this still open? I remember some web3-react upgrades went in with the widget.

context: I'm looking at https://github.com/Uniswap/interface/issues/2627 as a good starter task for vig or christine.

**Comment by tinaszheng** [comment]
looks like zach upgraded to v8 for widgets already!

**Comment by NoahZinsmeister** [comment]
well, v6 is still used in the non-widget part of the app - we probably want to migrate that as well! doesn't have to be to v8 of course, but it should be upgraded on some time frame as it's going to be deprecated

**Comment by vm** [comment]
I would be open to migrating us if it fits into the sprint, I'll chat with @willhennessy

**Comment by willhennessy** [comment]
yes perfect, thanks for volunteering! after you upgrade, then you can tackle the blocked issue too https://github.com/Uniswap/interface/issues/2627

**Comment by vm** [comment]
done!
