### ISSUE TITLE
Add on-hover tooltips for tx details

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#3118]
Add on-hover tooltips to educate users about the line items in transaction details

We already have a component for this called `MouseoverTooltip`. Here is an [example](https://github.com/Uniswap/interface/blob/9e1a775c137ac826ba9affe0f2d702ed61f386c9/src/components/CurrencyInputPanel/FiatValue.tsx#L46) of how to use it.

We should add a tooltip to the text area of each of the four line items below.

<img width="514" alt="Screen Shot 2022-01-13 at 10 16 34 PM" src="https://user-images.githubusercontent.com/5455577/149448226-3526b2c0-a72f-4978-89b6-846b0473405b.png">

**Text strings to use in the tooltip**
- [ ]  Expected Output
    - “The amount you expect to receive at the current market price. You may receive less or more if the market price changes while your transaction is pending.”
- [ ]  Price Impact
    - “The impact your trade has on the market price of this pool.”
- [ ]  Minimum received after slippage (0.50%)
    - “The minimum amount you are guaranteed to receive. If the price slips any further, your transaction will revert.”
- [ ]  Network fee
    - “The fee paid to miners who process your transaction. This must be paid in {ETH | MATIC}.”   (switch native token depending on network)

**Comment by 0xlucius** [comment]
Hey, I went ahead and implemented this and realized I forgot to ask here first. Will open a pull request when I get a go ahead here : )
