### ISSUE TITLE
Auto Router icon not appearing on mobile

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#3138]
**Bug Description**
When you expand the transaction details, the Auto Router box is missing the Auto Router icon

**Device**
 iOS latest version. Repro'd in both the Chrome browser and Coinbase browser..

**Steps to Reproduce**
1. app.uniswap.org
2. get a quote like DAI:ETH
3. expand the transaction details

observe there is no Auto Router icon. there should be, to the left of the text "auto router"

![IMG_65208C39A18D-1](https://user-images.githubusercontent.com/5455577/149821696-ddc534c3-dea2-4721-bed4-926e9ad6620d.jpeg)

**Comment by Udai1931** [comment]
Hey @willhennessy, Can i try to fix this?

**Comment by willhennessy** [comment]
yes please!

**Comment by sarahmajeed** [comment]
Hey @willhennessy, after reproducing, I don't see this bug. i see the icon placed on the left? Has this bug already been resolved?

**Comment by curly210102** [comment]
<img width="587" alt="Screen Shot 2022-03-06 at 11 39 54 AM" src="https://user-images.githubusercontent.com/76864176/156908264-d1bace87-0ebb-4100-a43e-2830c33e1b44.png">

GasEstimateBadge Tooltip contains same inline svg asset which uses LinearGradient and url(id). When id is duplicate in DOM, Safari only recognizes and remember the first one. 

Whe dropdown closed, the GasEstimateBadge removed at same time, Safari can not find the LinearGradient element the id related to.

<img width="502" alt="Screen Shot 2022-03-06 at 11 40 01 AM" src="https://user-images.githubusercontent.com/76864176/156908368-3b4594ea-c3dd-4e1d-af2e-5eb1c0816d96.png">

react-scripts [disabled the svgo](https://github.com/facebook/create-react-app/pull/5062) which can solve id collisions by [customization](https://github.com/svg/svgo/issues/674), in other words, react-scripts only do work to transform svg asset to ReactComponent, without any change to svg asset, and the id should be isolated in ReactComponent instance.
>  Edit by your own the SVG and use a hook to get a unique ID by component instance.
Refer to https://github.com/gregberge/svgr/issues/150#issuecomment-568279052

**Comment by curly210102** [comment]
<img width="600" alt="Screen Shot 2022-03-09 at 10 16 36 AM" src="https://user-images.githubusercontent.com/76864176/157359494-e950b35b-55cc-40f2-a8cd-3c1db83b83ca.png">

the ID is in auto_router.svg, you can locate the duplicate ID by `document.querySelectorAll("#gradient1")` after best price fetch.

**Comment by moodysalem** [comment]
I would love to see a tracking issue created with Safari (maybe WebKit [here](https://bugs.webkit.org/)?) since this is only an issue affecting mobile Safari
