### ISSUE TITLE
Tokens breaking auto router

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#3260]
**Bug Description**
There are some tokens (on FOT mainly) that break the auto router, and simply display "No Liquidity"
EX.
CAT 0x3734dc0d241b5ad886fa6bff45ffa67252ac0e89
there is no issues that I see with other pools. just one pool V2 WETH/CAT
RYOSHI 0x777E2ae845272a2F540ebf6a3D03734A5a8f618e
Both are only on V2
I'll post more when I see

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/swap?chain=mainnet
2. Click on load token CAT 0x3734dc0d241b5ad886fa6bff45ffa67252ac0e89
3. try to buy with ETH  load with auto router and with auto router turned off
   ...

**Expected Behavior**
Auto route to the only pool on V2

**Additional Context**
![image](https://user-images.githubusercontent.com/60412342/153104116-19ce7912-b8a9-4f9b-a01a-0afda5d5dc57.png)
![image](https://user-images.githubusercontent.com/60412342/153104116-19ce7912-b8a9-4f9b-a01a-0afda5d5dc57.png)
![image](https://user-images.githubusercontent.com/60412342/153104278-64a3b8a4-49a5-4b90-81d7-212edea0a7d1.png)
![image](https://user-images.githubusercontent.com/60412342/153104275-a0b7acab-c828-44c6-9023-bc73ad04735a.png)
![image](https://user-images.githubusercontent.com/60412342/153104612-08d24812-c978-49c0-b38b-82cb387b4d69.png)

**Comment by donoceidon** [comment]
https://github.com/Uniswap/interface/issues/3322#issuecomment-1045052893

**Comment by willpote** [comment]
Both tokens can now be swapped, resolving

![Screen Shot 2022-02-23 at 3 53 21 PM](https://user-images.githubusercontent.com/81638931/155406533-7c0f5e01-a2d3-4443-b666-06a72fa4a218.png)
![Screen Shot 2022-02-23 at 3 53 11 PM](https://user-images.githubusercontent.com/81638931/155406534-391076f2-6bf8-4b4b-9d23-b711456e8c93.png)
