### ISSUE TITLE
Bad link in help.uniswap.org

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#3266]
**Bug Description**
@willhennessy 
Couldn't find the pages for help in the code.
https://help.uniswap.org/en/articles/5455536-do-i-get-liquidated-if-the-price-goes-outside-of-my-range#:~:text=No%20%E2%80%94%20there%20are%20no%20liquidations,in%20the%20less%20valuable%20asset.&text=This%20means%20your%20position%20will,price%20comes%20back%20in%20range

the MP4 link goes to unauthorized 

**Steps to Reproduce**

1. Go to https://help.uniswap.org/en/articles/5455536-do-i-get-liquidated-if-the-price-goes-outside-of-my-range#:~:text=No%20%E2%80%94%20there%20are%20no%20liquidations,in%20the%20less%20valuable%20asset.&text=This%20means%20your%20position%20will,price%20comes%20back%20in%20range
2. Click on Bottom MP4 link "visualization"
   ...

**Expected Behavior**
opens mp4

**Additional Context**
![image](https://user-images.githubusercontent.com/60412342/153284113-97d42184-cf9a-430d-9119-331d4ef3d041.png)
![image](https://user-images.githubusercontent.com/60412342/153284116-c30a8e63-5016-4763-a69e-a03f7412b224.png)

**Comment by willhennessy** [comment]
fixed, thanks rachel!
