### ISSUE TITLE
Para ParaToken 0x32879b5c0fdbc2a81597f019717b412b9d755a09 Uniswap Auto API Router "Insufficient Liquidity For This Trade" Issue

### ISSUE THREAD

**Issue by leetolleson** [Uniswap/interface#3322]
**Bug Description**
Uniswap Auto API Router not working. Causes "Insufficient liquidity for this trade" message when attempting trade. Will not permit trade with Auto API Router on. 

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/swap?chain=mainnet
2. Auto API Router in the on position
3. Attempt swap with Ethereum and ParaToken (ParaToken Contract address: 0x32879b5c0fdbc2a81597f019717b412b9d755a09) 
   ...

**Expected Behavior**
"Insufficient Liquidity for this trade" appears when the Auto API router is on. 

**Additional Context**
Bug occurs on all mobile/desktop/browser environments

![Screen Shot 2022-02-16 at 11 10 02 AM](https://user-images.githubusercontent.com/99800889/154328782-b2ed6b0b-d06a-4073-b3c1-eebf0b2d1c68.png)
![Screen Shot 2022-02-16 at 11 10 11 AM](https://user-images.githubusercontent.com/99800889/154328828-28cfc07c-a444-42c7-84e9-8a942561b903.png)

Swap only works if Auto API router is turned off. 

![Screen Shot 2022-02-16 at 11 10 20 AM](https://user-images.githubusercontent.com/99800889/154331815-67c5d1af-f3df-4b04-93d1-85b901019b05.png)

**Comment by rileyg98** [comment]
Same issue as Holdenomics - #3316

**Comment by donoceidon** [comment]
Same issue with OBLOX

**Comment by willpote** [comment]
Pushed a fix out for this, and all the tokens mentioned can now be swapped. Resolving

![Screen Shot 2022-02-23 at 3 52 20 PM](https://user-images.githubusercontent.com/81638931/155406368-d67913ab-b33d-473a-ac87-3edf54053768.png)
![Screen Shot 2022-02-23 at 3 52 07 PM](https://user-images.githubusercontent.com/81638931/155406370-7c5a13c4-7874-4536-bba8-6cb2464d398c.png)
![Screen Shot 2022-02-23 at 3 51 56 PM](https://user-images.githubusercontent.com/81638931/155406371-9010d6fa-fdd7-4688-9787-1826f31eecb6.png)
.
