### ISSUE TITLE
Accessing Metamask thru Uniswap

### ISSUE THREAD

**Issue by Woodguy265** [Uniswap/interface#3336]
**Bug DescriptionI**
A clear and concise description of the bug.
I am trying to access my Metamask account thru Uniswap. When the click on select wallet it just shows that its initializing and doesn't connect. When I try to go back and try it again it show Error connecting. Can you tell me what I can do to solve this? Thanks.
**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by Woodguy265** [comment]
Not sure how to do that. I can’t open my wallet. Thanks.

Tom Leister
Leisters Furniture Inc.
433 Ridge Avenue
Hanover, PA  17331
***@***.******@***.***>
phone:  717-632-8177
fax:  717-632-8850

**Comment by Bleujj1** [comment]
I have once experience this with my trezor wallet.. you will need to debug
your wallet with a bech13. Then you reboot your device and connect it to
chrome on your Laptop.. I can help You with the link all you have to do is
to follow the link

**Comment by Bleujj1** [comment]
When you are ready let me know. I can get you an ellipal bech13 link to
synchronize your wallet and debug. All you have to do is to follow the link
till you get synchronize wallet and then you click on it

**Comment by Bleujj1** [comment]
Hope you have been able to resolve your issues?

**Comment by callil** [comment]
Closing due to personal information included in bug and lack of details. @Woodguy265 Please use the support team in discord to troubleshoot.
