### ISSUE TITLE
Mobile layout: hide closed positions disappears

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#3344]
**Bug Description**
On mobile devices, the 'Hide closed positions' toggle disappears due to overflow layout.

**Steps to Reproduce**

1. Go to /pool page
2. Assuming you have past LP positions you will see this on desktop
![Uniswap-Interface (1)](https://user-images.githubusercontent.com/5455577/155240554-3bbd9096-7eee-4f02-960a-49e4c22ff2f1.png)

but on mobile you will see this
![Uniswap-Interface](https://user-images.githubusercontent.com/5455577/155240530-26c754e1-febc-427d-82f1-612dcbd0aa41.png)

notice the 'hide closed positions' toggle disappears on mobile. We should keep that option because for users with a great number of positions, the request will actually time out. If the toggle does not fit within the white box next to "Your Positions" then it can overflow to its own line outside of and above the white box.

**Comment by behnammohammadkhani** [comment]
@willhennessy , is this bug Fixed? I'm ready to PR

**Comment by willhennessy** [comment]
Fantastic! I don’t think it’s fixed yet. Would love to see the PR

**Comment by behnammohammadkhani** [comment]
@willhennessy please check the related PR, would like to see your opinion :)

**Comment by ghgoodreau** [comment]
@willhennessy @behnammohammadkhani Hey! I took a shot at fixing this as well. Please see the attached MR.

**Comment by ghgoodreau** [comment]
This issue can now be closed since #3858 was merged @willhennessy
