### ISSUE TITLE
widgets.js not supported

### ISSUE THREAD

**Issue by epomatti** [Uniswap/interface#3370]
**Bug Description**

Getting this error when adding the widget component to a new Next.js project:

```
error - Error [ERR_REQUIRE_ESM]: require() of ES Module /home/pomatti/pjs/uniswap/uniswap-widget/node_modules/@uniswap/widgets/node_modules/@web3-react/core/dist/cjs/index.js from /home/pomatti/pjs/uniswap/uniswap-widget/node_modules/@uniswap/widgets/dist/widgets.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/pomatti/pjs/uniswap/uniswap-widget/node_modules/@uniswap/widgets/node_modules/@web3-react/core/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

**Steps to Reproduce**

1. Create new Next project `npx create-next-app@latest`.
2. Add the widget to the project https://docs.uniswap.org/sdk/widgets/swap-widget#installing-library.
3. Start Next server and the error happens.

**Expected Behavior**

Widget should work as per documentation.

**Comment by DecoratedWings** [comment]
I am having the same issues. Alternative for uniswap specifically is to use the iframe for now until either a resolution is posted or I am able to solve this... 

Link to iframe docs in case anyone finds it useful: 
https://docs.uniswap.org/protocol/V2/guides/interface-integration/iframe-integration

**Comment by epomatti** [comment]
This was fixed a good time ago, when it was still on beta.

Use V3. https://docs.uniswap.org/sdk/widgets/swap-widget
