### ISSUE TITLE
Bug: there is still dust liquidity left but my positions shows closed

### ISSUE THREAD

**Issue by yichiehliu** [Uniswap/interface#3406]
**Bug Description**
When I closed my LPed position on uniswap, they will always left 1e-18 oSQTH of my LP position but I did click max on uniswap to close, and the oSQTH i take back when I close the LPed position is always less than the amount I put in, my LPed positions on uniswap showed “Closed” even though I have 1e-18 dust left there

**Steps to Reproduce**

1. Go to add liquidity 
2. Close the position
3. Check the exact token amounts of the opening position & closing position txs, the amount you put in is different from the amount you take back

**Expected Behavior**
The amount that I put in should be the same as the one I take back

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by NoahZinsmeister** [comment]
not a bug, v3 contracts round in favor of themselves to maintain solvency
