### ISSUE TITLE
"Insufficient liquidity for this trade" for V2 tokens.

### ISSUE THREAD

**Issue by DALHOUM-Ahmed** [Uniswap/interface#3500]
**Bug Description**
The attempt to swap several tokens with liquidity in v2 pools fails to find liquidity when using uniswap UI. The tokens in question are:
1- 0x275EB4F541b372EfF2244A444395685C32485368
2- 0x337c456d481D1C09E615Eeacc6F590e6d9C8FbAE
3- 0x91fe3594920F0a00F880791Db8fDAA95e2E060a3

**Steps to Reproduce**

1. Go to uniswap main UI page or use the direct link: https://app.uniswap.org/#/swap?use=v2&chain=mainnet&inputCurrency=ETH&outputCurrency=0x275eb4f541b372eff2244a444395685c32485368
2. Import token.
3. Switching auto-routing on or off doesn't change the behavior.

**Expected Behavior**
Active swap button.

**Additional Context**
Chrome Network section shows: {"detail":"No route found","errorCode":"NO_ROUTE","id":"11815"}
Similar issues are:
https://github.com/Uniswap/interface/issues/3316
https://github.com/Uniswap/interface/issues/3322
https://github.com/Uniswap/interface/issues/3260

![d1](https://user-images.githubusercontent.com/59100760/157834862-32292049-f03a-4ba8-9964-82063140645c.jpg)
![d2](https://user-images.githubusercontent.com/59100760/157836153-635f5321-b0ba-4cb7-a49a-77987be13b00.jpg)
![d3](https://user-images.githubusercontent.com/59100760/157836207-f93d4756-3b07-45b2-996d-8e4e8262de3f.jpg)

**Comment by Rachel-Eichenberger** [comment]
@willpote 
Hey sorry to tag, but seems your the auto router wizard :)
so adding to the above I have token "Pass The Loot" address  0xE2188e5f335A786a487E468D07d388A9301c14d6
toggling the auto router switch doesn't help



same issue showing no route in v2, v3 yet plenty of LQ
![image](https://user-images.githubusercontent.com/60412342/158516781-0e89d049-e8e1-432d-83dc-101265deeab2.png)
![image](https://user-images.githubusercontent.com/60412342/158516792-5b530c77-667e-41fe-b170-bf235f04f008.png)
![image](https://user-images.githubusercontent.com/60412342/158516807-508ac31b-4558-489f-8071-2b35a5cee1ed.png)

**Comment by Rachel-Eichenberger** [comment]
all 4 above do work on older version IPFS

https://bafybeigkgx3gq5yrrsyxpna2czlq3bc2ish2gk6yqh7v57kugehlq6qoly.ipfs.dweb.link/#/swap

**Comment by willpote** [comment]
All these tokens have 'anti snipe logic' that seems to block transfers unless `tx.origin == to`. This was causing the token validator (which flash loans tokens to validate them) to fail. I've updated the Auto Router to allow these tokens if they are specified as token in or token out. 

They can all be traded now

**Comment by codingkim100100** [comment]
> All these tokens have 'anti snipe logic' that seems to block transfers unless `tx.origin == to`. This was causing the token validator (which flash loans tokens to validate them) to fail. I've updated the Auto Router to allow these tokens if they are specified as token in or token out. 
> 
> They can all be traded now

What can be done for other contracts that have been using this type of antibot condition? Is the only solution a manual whitelist? Is there a smart contract, the token validator, that you can point me to so I can whitelist antibot?

**Comment by codingkim100100** [comment]
Since we offer AntiBot as a service to many contracts, I wonder if there is a contract associated with the auto router that we could whitelist to allow our antibot to ignore. IF there was such a contract, would this SwapRouter be it? 0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45

**Comment by willpote** [comment]
> What can be done for other contracts that have been using this type of antibot condition? Is the only solution a manual whitelist?

I changed the auto router so that if a user specifically chooses a token with this logic it can be swapped. i.e. `AntiSnipeToken --> ... --> SomeToken` will work, and `SomeToken --> ... --> AntiSnipeToken` will work. The only case that won't work is `SomeToken --> ... --> AntiSnipeToken --> ... --> SomeToken`

> Since we offer AntiBot as a service to many contracts, I wonder if there is a contract associated with the auto router that we could whitelist to allow our antibot to ignore. IF there was such a contract, would this SwapRouter be it? 0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45

Yes, this is the contract to allowlist: 0xb5ee1690b7dcc7859771148d0889be838fe108e0
