### ISSUE TITLE
Shinja token using wrong decimals

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#3616]
**Bug Description**
Shinja Token 0xab167e816e4d76089119900e941befdfa37d6b32 loads with wrong decimals
loads with 18 but is 9
CoinMarket cap has wrong decimals too
https://api.coinmarketcap.com/data-api/v3/uniswap/all.json

**Steps to Reproduce**

1. Go to app.uniswap.org
2. Add 0xab167e816e4d76089119900e941befdfa37d6b32 token
   ...

**Expected Behavior**
shinja is 9 decimals

**Additional Context**
see below

**Comment by Rachel-Eichenberger** [comment]
@willhennessy 
so this has the same issue as here where it's adding 9 decimals, and it is doing it to the transactions too
so if you sell 1000 tokens it actually turns it into 1000000000000 tokens

https://github.com/Uniswap/interface/issues/2751

**Comment by alexdorsch** [comment]
#3661

**Comment by Rachel-Eichenberger** [comment]
@zzmp 
sorry for the ping, but since the token balance fix went live I wanted to push this
as it's passing through to tx
but this token is a 9 decimal token, and the UI is treating it as 18
current UI quote for .1 ETH
95448000000000000
![image](https://user-images.githubusercontent.com/60412342/163103240-13976dad-48e7-4c1e-b5f7-295e5cb9592e.png)
call to get amounts
95448074.683849614736724728
![image](https://user-images.githubusercontent.com/60412342/163103579-e566eeab-1a66-486c-82a4-37935cdf238f.png)

**Comment by Rachel-Eichenberger** [comment]
Bug Description
Saint Token0x6fc5af63990aa9e5c5543f5cd8ed148bfa6d9d19  loads with wrong decimals when swapping From token to ETH
loads with 18 but is 9
CoinMarket cap has wrong decimals too (showing 18)
https://api.coinmarketcap.com/data-api/v3/uniswap/all.json

Steps to Reproduce

Go to app.uniswap.org
Add 0x6fc5af63990aa9e5c5543f5cd8ed148bfa6d9d19 token
...


Expected Behavior
saint is 9 decimals

![image](https://user-images.githubusercontent.com/60412342/168413056-15bcc594-71a1-4920-916c-df2f76de8bd3.png)
![image](https://user-images.githubusercontent.com/60412342/168413059-3af425dc-626d-4715-89bb-d6d4dab2e6b3.png)

**Comment by Rachel-Eichenberger** [comment]
Testing current fix with community by

going into to Manage Tokens Lists Section
scroll down and find the CoinMarketCap Token List
click on the little gear box, and then click remove.

**Comment by Rachel-Eichenberger** [comment]
@beltex63 
Try the Above fix

**Comment by Rachel-Eichenberger** [comment]
Merging to issue
https://github.com/Uniswap/interface/issues/3973
