### ISSUE TITLE
Widget broken when using React 18 - ./jsx-runtime.js is not exported from package

### ISSUE THREAD

**Issue by epomatti** [Uniswap/interface#3674]
**Bug Description**

Getting the following error then running the Widget with the recent React 18 release.

```
./node_modules/.pnpm/@uniswap+widgets@1.0.0_7db2c8304055b90a620054d8ff556e3c/node_modules/@uniswap/widgets/dist/index.js:22:0
Module not found: Package path ./jsx-runtime.js is not exported from package 
```

**Steps to Reproduce**

Running the widget will trigger the error when using React 18.

```js
<div className="Uniswap">
  <SwapWidget
    provider={provider}
    jsonRpcEndpoint={jsonRpcEndpoint}
  />
</div>
```

Workaround is to use React 17.

**Comment by JCcastagne** [comment]
Hi epomatti,

Been having this issue while trying to install @uniswap/widgets with react 18. I believe it is uniswap demanding to have at least React V17.0.1.

Here's the error when trying to install the uniwswap widget in a brand new react18 project:

```
user@user random-react-project % npm install @uniswap/widgets
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-uniswap-widget@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from @uniswap/widgets@1.0.10
npm ERR! node_modules/@uniswap/widgets
npm ERR!   @uniswap/widgets@"*" from the root project
npm ERR! 

```

Seeing your issue, I believe it's just uniswap not having their widgets updated for React18
