### ISSUE TITLE
Quote blocked by Cors policy

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#3678]
**Bug Description**
Users in Korea (as far as i've seen, maybe outside as well)

UI when getting quote is blocked by cors policy (see image below)
seems to only happen to then when trying to trade their new token

didn't see any aws issues , and kinda lost with this one
I have been unable to reproduce, but according to User/token owner no one in their group can swap
and only see the "insufficient liquidity..." in the grey button 

**Steps to Reproduce**

1. Go to app.uniswap.org via korea vpn (if possible)
2. Load token LOKA "0x61e90a50137e1f645c9ef4a0d3a4f01477738406"
3. doesn't load price for korea.
   ...

**Expected Behavior**
receive quote when inputting amount

**Additional Context**
![image](https://user-images.githubusercontent.com/60412342/162098613-1ddedb18-d963-4ccf-856e-c8aa43947a3f.png)

![image](https://user-images.githubusercontent.com/60412342/162101061-8f06a648-32ad-46f0-9575-c00c04718aad.png)

**Comment by stevibiel** [comment]
I'm able to repro this with a South Korean VPN

<img width="1327" alt="Screen Shot 2022-05-03 at 4 46 18 PM" src="https://user-images.githubusercontent.com/25967618/166563701-d7f787b4-13ac-4593-89ee-09bb4267de80.png">

**Comment by willpote** [comment]
@stevibiel Would you mind testing again on your VPN? I've made a change that hopefully fixes this.

**Comment by stevibiel** [comment]
@willpote yes, this token price now loads when I use the VPN for South Korea. thank you!

**Comment by Rachel-Eichenberger** [comment]
@willpote @stevibiel 
Thank you, sorry, my email on phone broke so I missed this. I've reached out to the community to verify without VPN, I will close after. Thanks again

**Comment by Rachel-Eichenberger** [comment]
I received confirmation that it's working without VPN thanks

**Comment by b4dPot4to** [comment]
I'm still having this issue when I'm trying to swap any token 
![image](https://github.com/Uniswap/interface/assets/112569797/a835082c-aa68-4f58-9e51-1a1783a611d5)

**Comment by ihrahat0** [comment]
Getting same issue 409 cors on uniswap graphql.
1) i have change origin
2) content type
3) add proxy in package json 
these solution didn'nt work for me is there any issue with package upgrade or downgrade??
