### ISSUE TITLE
Remove portis

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#3680]
Extremely low usage of Portis and the company has rebranded to Magic. 

Please remove Portis from the UI and delete all related code.

**Comment by MarkCarbajal** [comment]
Hello, can you assign this to me?

**Comment by willhennessy** [comment]
Yeah! Thanks Mark! 🦄

**Comment by Rachel-Eichenberger** [comment]
> Portis

@willhennessy 
So we have had a bunch of users asking about this removal, wanted to make sure the correct wallet support was removed. It appears Fortmatic was the one re-branding to MAGIC

![image](https://user-images.githubusercontent.com/60412342/169364374-742b24b6-49d0-4231-a3cf-814359c31c85.png)

**Comment by Rachel-Eichenberger** [comment]
> Yes this was intentional because Portis has very low usage numbers. How many people have you heard from about Portis? Happy to consider the feedback!

I would say like 5- 10 have showed up in the discord
