### ISSUE TITLE
Unable to select Network on mobile device after clicking Connect Wallet

### ISSUE THREAD

**Issue by brunocrosier** [Uniswap/interface#3690]
**Bug Description**
On the  Swap page, it is impossible to open the Network selector while on mobile if you have previously opened and closed a Currency Input component or the Connect Wallet dialog 

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/swap?chain=polygon on a device with no hover support (i.e. a mobile)
2. Click on MATIC
3. Either select a currency or just close the dialog
4. Try to open the Network Select. You won't be able to

**Expected Behavior**
Should be able to open and close the Network Select at all times

**Additional Context**
I have investigated this and will create a PR for it. The cause of the issue is that the `NetworkSelect` component is currently only ever toggled open / closed based on hover, which does not work in the same way for mobiles. PR will make it possible to toggle the state based on a click as well as hover.

**Comment by jbeanz** [comment]
can you assign this to me?

**Comment by brunocrosier** [comment]
> can you assign this to me? i've worked on similar issues

thanks! I have a PR which fixes this, which I will push in a couple of hours. Will tag you in it for review :)

**Comment by brunocrosier** [comment]
Hi @jbeanz please feel free to take a look at https://github.com/Uniswap/interface/pull/3698
