### ISSUE TITLE
"For" should be translated differently under different context in zh-TW and zh-CN

### ISSUE THREAD

**Issue by 0xYYY** [Uniswap/interface#3741]
**Bug Description**
Incorrect zh-TW/zh-CN translation for `"For"` on the swap page. Currently, it is being translated to `"贊成"`/`"赞成"` (meaning "agree").

**Expected Behavior**
`"For"` should be translated to `"獲得"`/`"获得"`  (meaning "obtain") on the swap page (`src/lib/components/Swap/Output.tsx`).

**Extra Context**
Need a way to distinguish between two context, `src/lib/components/Swap/Output.tsx` and `src/pages/Vote/VotePage.tsx`, in the translation file.

https://github.com/Uniswap/interface/blob/71aebf33db1bc5f2da8e3aac3a9579437d603dc1/src/locales/zh-TW.po#L869-L872

https://github.com/Uniswap/interface/blob/71aebf33db1bc5f2da8e3aac3a9579437d603dc1/src/locales/zh-CN.po#L869-L872

**Comment by NoahZinsmeister** [comment]
thanks for flagging! see https://github.com/Uniswap/interface/blob/main/CONTRIBUTING.md#translations for contributing translation changes
