### ISSUE TITLE
Connection failure from Coinbase wallet

### ISSUE THREAD

**Issue by JMAC2076** [Uniswap/interface#3966]
**Bug Description**
Fails to connect when I click the dapp

**Steps to Reproduce**

1. Go to dapps
2. Click on uniswap, or enter the URL 
   ...

**Expected Behavior**
Fails to connect 
![Screenshot_20220623-213600](https://user-images.githubusercontent.com/108107372/175446504-56dc0c01-d4f1-4a28-8dba-273843daa535.png)

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by vm** [comment]
this should be resolved, but let us know if not
