### ISSUE TITLE
Stopped supporting network URL param for uniswap v3 position

### ISSUE THREAD

**Issue by YegorZaremba** [Uniswap/interface#4029]
**Bug Description**

URL contains Polygon, but Ethereum is displayed in the right dropdown
![image](https://user-images.githubusercontent.com/31797554/177262059-901d6933-9a4a-4cba-adcd-15c58e41f2ad.png)

**Steps to Reproduce**

1. Open Google Chrome Incognito window
2. Go to https://app.uniswap.org/#/pool/163474?chain=polygon
   ...

**Expected Behavior**
See position on polygon network, but currently showing ethereum mainnet

**Additional Context**
I guess recent release broke sth, cause It worked a week ago

**Comment by vm** [comment]
https://github.com/Uniswap/interface/pull/4019#pullrequestreview-1036140730

**Comment by YegorZaremba** [comment]
@vm Thanks for your changes, but still reproduce, could you please reopen
