### ISSUE TITLE
Swap boxes have incorrect bottom padding

### ISSUE THREAD

**Issue by callil** [Uniswap/interface#4063]
The swap UI has incorrect bottom padding beneath the balance section:

Current:
<img width="251" alt="Screen Shot 2022-07-08 at 11 00 36 AM" src="https://user-images.githubusercontent.com/1355319/178018535-b000ef97-f005-406a-9af3-b64eee6d68da.png">

Expected:
<img width="238" alt="Screen Shot 2022-07-08 at 11 02 57 AM" src="https://user-images.githubusercontent.com/1355319/178018970-509ea876-4d40-49b5-a759-954a4be93394.png">

**Comment by kayleegeorge** [comment]
fixed on next deploy

<img width="458" alt="Screen Shot 2022-07-11 at 5 11 06 PM" src="https://user-images.githubusercontent.com/62825936/178359212-b468ba4a-d2c3-4e4d-a5c7-e70d82fbc218.png">
