### ISSUE TITLE
Network selector should not close on click

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#4133]
**Bug Description**
When you click on the network selector, it closes. It should remain open, because only on-hover should trigger open/close.

**Steps to Reproduce**

1. Drag your mouse over the network 
2. It will expand when you hover
3. But many users don't know that, so they instinctively plan to click on it.
4. The click causes the selector to close, which is certainly not what the user intended.

**Expected Behavior**
The network should selector should open on-hover, and close when hover moves off the component.  Clicking should have no effect.

**Comment by vm** [comment]
what about on mobile?

**Comment by willhennessy** [comment]
Thanks yeah mobile should respond to clicks. I was only thinking desktop
when I wrote this.



Will Hennessy

Product

E: ***@***.***

Uniswap Labs <http://uniswap.org/> | Careers
<https://boards.greenhouse.io/uniswaplabs>


Sent via Superhuman iOS ***@***.***>
