### ISSUE TITLE
Remove Liquidity tests fail sporadically

### ISSUE THREAD

**Issue by vm** [Uniswap/interface#4336]
**Bug Description**
The e2e tests for remove-liquidity fail randomly, might be related to window reloading on that page?

**Steps to Reproduce**
Try to run the test a bunch of times and it'll eventually fail.

**Expected Behavior**
The test should pass.

**Additional Context**
You can look for what changes were made recently in swap.test.ts, may need similar changes.

**Comment by ashutosh887** [comment]
I would like to work on this @vm

**Comment by brunovjk** [comment]
Hello, is this issue still open?
