### ISSUE TITLE
In add liquidity, full range button only sets min price

### ISSUE THREAD

**Issue by justindomingue** [Uniswap/interface#4578]
**Bug Description**
In add liquidity, full range button only sets min price, max price does not change

**Steps to Reproduce**

1. Go to [add liquidity page](https://app.uniswap.org/#/add/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/3000?maxPrice=3091.785200&chain=mainnet)
2. Click on `Full Range`

**Expected Behavior**
Max price is set to infinity

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by gnewfield** [comment]
This was resolved by [6136](https://github.com/Uniswap/interface/pull/6136) and is currently working. Manually verified with below. [Link](https://app.uniswap.org/#/add/ETH/0x6B175474E89094C44Da98b954EedeAC495271d0F/3000?minPrice=0.0000000000000000000000000000000000000029543&maxPrice=338490000000000000000000000000000000000) to reproduce.

<img width="900" alt="Screenshot 2023-07-26 at 2 32 07 PM" src="https://github.com/Uniswap/interface/assets/18626088/86d4f399-32f3-4c5d-b1ec-6a3a699c971f">
