### ISSUE TITLE
UI not allowing a token to load after already imported

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#5352]
**Bug Description**
The UI is breaking when a user who has already put in a token address, next time user searches the token will not come up.
clearing cookies, cache and hard refresh does not help

currently only known work around is to use a version via IPFS
or 
force the UI via custom linking
[https://app.uniswap.org/#/swap?inputCurrency=ETH&outputCurrency=](https://app.uniswap.org/#/swap?inputCurrency=ETH&outputCurrency=0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a)

**Steps to Reproduce**

1. Go to app.uniswap.org import a token you haven't imported before, it will show
2. Close and refresh the page and try to search nothing comes up
   ...

**Expected Behavior**
UI should be able to find token by address anytime

**Additional Context**

Token currently loaded
![image](https://user-images.githubusercontent.com/60412342/202919475-acdd1682-7302-4d04-b5ce-0c079a94fcbe.png)

same page, no reload or anything, search for token address (already loaded 0xc5a9bc46a7dbe1c6de493e84a18f02e70e2c5a32)
will also happen on refresh
![image](https://user-images.githubusercontent.com/60412342/202919511-1e572aad-9c48-4d17-a42a-5e07dcecb436.png)

**Comment by Rachel-Eichenberger** [comment]
seems focused on current browser instance, opening a new window seems to start the issue over, token shows up first time, then not again after imported

**Comment by callil** [comment]
@Rachel-Eichenberger This was closed by a few recent commits: https://github.com/Uniswap/interface/commit/dee808cc57c0ed97fe4a09261bff9db60f3bcff2 and https://github.com/Uniswap/interface/commit/3d820d39b7693928fd826cf171c8afd988ead9ae

Can you check if this solved the issue?

**Comment by Rachel-Eichenberger** [comment]
@callil So yeah, I noticed late last night, It looks like it's good on my end, haven't seen the it happen again, and tested quite a few tokens. Thanks everyone
