### ISSUE TITLE
UI crashes if bad ENS avatar link

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#5812]
**Bug Description**
If a user has poorly set ENS Avatar, or if NFT image url is not standardized then the UI will crash. (steps to fix below image)

**Steps to Reproduce**

1. Go to ENS and setup avatar without NFT id, or use non standard NFT
2. Try to load app.uniswap.org (image below)
   ...

**Expected Behavior**
UI could ignore ENS if error loading NFT Avatar

**Additional Context**
![image](https://user-images.githubusercontent.com/60412342/211666856-3d9fe8ad-2ab3-4638-976d-28ba5b9562eb.png)

**How to fix**
you would just have to go to https://app.ens.domains/
connect your wallet, and open the ENS name that contains the avatar. 
![image](https://user-images.githubusercontent.com/60412342/211667551-76a25797-e942-443f-b862-a3b43128e0f5.png)
From there its easy to change.

fixing you would want to use this guide https://medium.com/the-ethereum-name-service/step-by-step-guide-to-setting-an-nft-as-your-ens-profile-avatar-3562d39567fc as there is a format needed. Also this requires semi standard NFT if something is odd about the image link it can still fail.

Other option is by removing the avatar.

**Comment by grabbou** [comment]
Hey!
Thank you for reporting this bug and providing such a comprehensive explanation! It's a very fortunate coincidence that I started working on this particular bug hours before your report and opened up a PR #5810 that we're planning to ship in the next few days!
