### ISSUE TITLE
UI pool position upper and lower prices to short

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#5813]
**Bug Description**
![image](https://user-images.githubusercontent.com/60412342/211671888-f0fee6a3-fab1-4ea3-ac8d-8de1c9585a3e.png)

Perhaps the lower and upper prices have been shortened for the mobile UI, However it would be nice for desktop to extend the places out more, as some views won't even show the price. (like above)

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/pool/383614
2. Click on USDC for usdc value in ETH
3. Doesn't show a real price as price is below 3 places
   ...

**Expected Behavior**
The lower places could be ok on mobile since space is always an issue, but perhaps we could get a switch case for Desktop to have more than 3 places, perhaps the old 7 places or 8..

**Comment by ArtemFrantsiian** [comment]
@Rachel-Eichenberger Im looking for ways to contribute. Is this issue available?

**Comment by Rachel-Eichenberger** [comment]
Looks like this has been fixed
