### ISSUE TITLE
RPC error when creating or adding a position in v4.200.2

### ISSUE THREAD

**Issue by kallydev** [Uniswap/interface#6089]
**Bug Description**

Creating or adding liquidity to a position is not available in v4.200.2 but works fine in v4.200.1.

**Steps to Reproduce**

### v4.200.2

https://bafybeigecqkvhdfhplp74xvgtst7firstgkpmyxl6ys3fvntw5xvk6gk74.ipfs.cf-ipfs.com/

### v4.200.1

https://bafybeicnf6njex3i2u5adegdzb2exxor63hygebd4s2hkz5y2xhp46un2i.ipfs.cf-ipfs.com/

1. Go to the `Pool`.
2. Click on `New Position`.
3. Select any token pair and add liquidity.

![image](https://user-images.githubusercontent.com/36319157/223452837-57266d08-eeb8-48c2-be93-0cf5d4ca2e07.png)

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/36319157/223450175-e41e2919-8fb7-48d9-978a-6c0a09e1e9dc.png">

**Expected Behavior**
Rollback to v4.200.1, or fix it.

**Additional Context**
The error occurs on desktop and mobile and can be reproduced on any currently supported network.

**Comment by JFrankfurt** [comment]
Thanks for reporting. We're working on this now.
