### ISSUE TITLE
Injected browser wallets not appearing on mobile

### ISSUE THREAD

**Issue by thomas-waite** [Uniswap/interface#6242]
**Bug Description**
Injected browser wallets are not appearing in the connection options on mobile (see screenshot). I've noticed it with my project, Dawn Wallet - we inject a provider into the webpage. When a user originally clicked on the `MetaMask` icon to connect, it would prompt our connection modal. 

Now, `MetaMask` does not appear and nor does any option to connect an `Injected/Browser` wallet. We are definitely injecting the provider and it works on other dapps as expected.

**Steps to Reproduce**
1. Download the Dawn Wallet Testflight: https://testflight.apple.com/join/UHmOJnNy 
2. Setup the Safari extension (onboarding in app)
3. Go to uniswap on Safari and try to connect

**Expected Behavior**
The MetaMask connection option should be available (Dawn's injected provider mimics MetaMask). When you click it, it would prompt Dawn's popup to appear.

**Additional Context**
What we now see on mobile (no MetaMask, which we override):
![Uniswap Interface](https://user-images.githubusercontent.com/20632187/227382156-a9cb20e8-5f09-47fa-a794-f19da1518757.png)

If it's useful context, we mimic MetaMask by adding a `isMetaMask` flag onto our injected provider; along with `isDawn`

**Comment by thomas-waite** [comment]
@tinaszheng, is there an update as to when the regression might be fixed? Our users can't currently access Uniswap (we're not yet in WalletConnect). If something needs to change on our side to accommodate a recent change, let us know :)

**Comment by tinaszheng** [comment]
@thomas-waite we just released a fix! Can you confirm if it's working on your end now? We also QAd with your TestFlight link so thank you for that!

**Comment by thomas-waite** [comment]
> 

Yep, we can connect and swap - thanks for sorting!
