### ISSUE TITLE
Issues with Tether approvals

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#6809]
**Bug Description**
Tether has a non standard approval, if approval amount is lower than what is needed to spend, then a Revoke is required before a new larger approval is made.

**Steps to Reproduce**

1. Go to app.uniswap.org
2. You Need a small approval allowance, and higher sale
3. try to approve for amount this will fail
   ...

**Expected Behavior**
a check for USDT should be performed, if approval < amount , then give revoke button to approve for 0 tokens, then the approval for a larger sum can take place

**Additional Context**

```
// To change the approve amount you first have to reduce the addresses`
//  allowance to zero by calling `approve(_spender, 0)` if it is not
//  already 0 to mitigate the race condition described here:
//  https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729

require(!((_value != 0) && (allowed[msg.sender][_spender] != 0)));                <--- (double not value)
```

**Comment by JFrankfurt** [comment]
I think someone was working on this recently--I'll look into that.

**Comment by Rachel-Eichenberger** [comment]
Excellent, thanks.

**Comment by JFrankfurt** [comment]
https://github.com/Uniswap/interface/pull/6730

**Comment by JFrankfurt** [comment]
this will go out with the next release

**Comment by Rachel-Eichenberger** [comment]
Thank you @JFrankfurt  
I will go ahead and close since your reference is here https://github.com/Uniswap/interface/pull/6730
