### ISSUE TITLE
UK connections being completely blocked from all subdomains except app.uniswap.org

### ISSUE THREAD

**Issue by JABirchall** [Uniswap/interface#7436]
As title says, uniswap is now blocking UK connections to subdomains of uniswap. except for app.uniswap.org

I dont know if this is intented from the PRs adding the banner, but i dont see anything specific to outright blocking UK connections, so i assume it isnt intended. 

The list includes

The main website: uniswap.org
Info.uniswap.org
blog.uniswap.org
help.uniswap.org

And maybe MANY others i dont know about.

Again, the only site accessable is app.uniswap.org

But also, in regards to compliance to the UK law, access to the info domain for liquidity etc, is required. The law is about providing details and info to UK clients. By blocking access you are doing the complete oppersite to what the law requires.

And as noted in the banner, uniswap is only a tool to trade the crypto and is not affiated with any crypto traded on uniswap. So i dont know why uniswap is blocking access to any of the subdomains.

**Comment by JABirchall** [comment]
Update, 

wallet.uniswap.org is also blocking UK connections

**Comment by cbachmeier** [comment]
UK service to http://info.uniswap.org/ has been restored

**Comment by JABirchall** [comment]
> UK service to http://info.uniswap.org/ has been restored

What about the other domains?
