### ISSUE TITLE
I get CORs error while sending request to https://api.uniswap.org/v2/quote

### ISSUE THREAD

**Issue by alchemist0803** [Uniswap/interface#7618]
**Bug Description**
Swap works fine in local environment.
But once it is deployed to server, I got below error.

>  Access to fetch at 'https://api.uniswap.org/v2/quote' from origin 'http://45.79.42.194:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Steps to Reproduce**

1. Go to http://45.79.42.194:3001/swap
2. Try to swap token
3. It will send above error in developer console.

**Comment by tinaszheng** [comment]
This is by design and not a bug, sorry!

**Comment by jblewnormal** [comment]
> This is by design and not a bug, sorry!

How would you recommend replacing the private API resources within the web interface like this one for folks working on a fork?

**Comment by Filicipa** [comment]
@tinaszheng Hello, i have a similar issue. Do you have any recomends about solve it?
