### ISSUE TITLE
run interface issue

### ISSUE THREAD

**Issue by burky721** [Uniswap/interface#7678]
ERROR in ../../packages/uniswap/src/config.ts
Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/levi/Documents/workspace/v3-interface/packages/uniswap/src/config.ts: "APPSFLYER_API_KEY" is not defined in ../../.env.defaults
  1 | import {
> 2 |   APPSFLYER_API_KEY,
    |   ^^^^^^^^^^^^^^^^^
  3 |   APPSFLYER_APP_ID,
  4 |   FIAT_ON_RAMP_API_URL,
  5 |   FIREBASE_APP_CHECK_DEBUG_TOKEN

how can I fix this？？

**Comment by bigbangbtc** [comment]
same problem here.

**Comment by bigbangbtc** [comment]
I think I solved that.
You can create `.env.default` file under project root.
And copy the configuration in config/jest-presets/jest/globals.js to the env file.
like this.

```
ALCHEMY_API_KEY = 'key'
AMPLITUDE_EXPERIMENTS_DEPLOYMENT_KEY = 'key'
APPSFLYER_API_KEY = 'key'
APPSFLYER_APP_ID = "123"
FIAT_ON_RAMP_API_URL = 'https://api.uniswap.org'
MOONPAY_API_KEY = 'key'
MOONPAY_API_URL = 'https://api.moonpay.com'
MOONPAY_WIDGET_API_URL = 'https://api.moonpay.com'
INFURA_PROJECT_ID = "123"
ONESIGNAL_APP_ID = "123"
QUICKNODE_BNB_RPC_URL = 'https://api.uniswap.org'
SENTRY_DSN = 'http://sentry.com'
SHAKE_CLIENT_ID = "123"
SHAKE_CLIENT_SECRET = "123"
SIMPLEHASH_API_KEY = 'key'
SIMPLEHASH_API_URL = 'https://api.simplehash.com'
STATSIG_PROXY_URL = 'https://api.statsig.com'
TEMP_SCANTASTIC_URL = 'https://api.uniswap.org'
TRADING_API_KEY = 'key'
TRADING_API_URL = 'https://api.uniswap.org'
UNISWAP_API_KEY = 'key'
UNISWAP_API_BASE_URL = 'https://api.uniswap.org'
UNISWAP_APP_URL = 'https://app.uniswap.org'
WALLETCONNECT_PROJECT_ID = "123"
UNITAGS_API_URL = 'https://api.uniswap.org/unitags'
FIREBASE_APP_CHECK_DEBUG_TOKEN = 'token'
```

They you're good to go.

**Comment by burky721** [comment]
> I think I solved that. You can create `.env.default` file under project root. And copy the configuration in config/jest-presets/jest/globals.js to the env file. like this.
> 
> ```
> ALCHEMY_API_KEY = 'key'
> AMPLITUDE_EXPERIMENTS_DEPLOYMENT_KEY = 'key'
> APPSFLYER_API_KEY = 'key'
> APPSFLYER_APP_ID = "123"
> FIAT_ON_RAMP_API_URL = 'https://api.uniswap.org'
> MOONPAY_API_KEY = 'key'
> MOONPAY_API_URL = 'https://api.moonpay.com'
> MOONPAY_WIDGET_API_URL = 'https://api.moonpay.com'
> INFURA_PROJECT_ID = "123"
> ONESIGNAL_APP_ID = "123"
> QUICKNODE_BNB_RPC_URL = 'https://api.uniswap.org'
> SENTRY_DSN = 'http://sentry.com'
> SHAKE_CLIENT_ID = "123"
> SHAKE_CLIENT_SECRET = "123"
> SIMPLEHASH_API_KEY = 'key'
> SIMPLEHASH_API_URL = 'https://api.simplehash.com'
> STATSIG_PROXY_URL = 'https://api.statsig.com'
> TEMP_SCANTASTIC_URL = 'https://api.uniswap.org'
> TRADING_API_KEY = 'key'
> TRADING_API_URL = 'https://api.uniswap.org'
> UNISWAP_API_KEY = 'key'
> UNISWAP_API_BASE_URL = 'https://api.uniswap.org'
> UNISWAP_APP_URL = 'https://app.uniswap.org'
> WALLETCONNECT_PROJECT_ID = "123"
> UNITAGS_API_URL = 'https://api.uniswap.org/unitags'
> FIREBASE_APP_CHECK_DEBUG_TOKEN = 'token'
> ```
> 
> They you're good to go.

Will try

**Comment by burky721** [comment]
It seems wired but solved ,thx bro!

**Comment by rishav-eulb** [comment]
do we need actual appsflyer api key?

**Comment by rishav-eulb** [comment]
or just copy pasting above object will work??

**Comment by bigbangbtc** [comment]
> or just copy pasting above object will work??

just copy and paste

**Comment by sanghunka** [comment]
create `.env.defaults` file under project root
Not `.env.default`

**Comment by n00b21337** [comment]
I don see how this helps I still get the same error and actually nothing is set with above solution. As that key is still missing

![image](https://github.com/user-attachments/assets/3d144e2e-1153-4e36-ab20-688abe29c4d0)
