### ISSUE TITLE
In sepolia, token information is undefined

### ISSUE THREAD

**Issue by zkcarl** [Uniswap/interface#7698]
path : interface/apps/web/src/pages/AddLiquidity/index.tsx
![image](https://github.com/Uniswap/interface/assets/166362586/ddbe1a98-0dbf-461c-9951-4e6df714f79b)
get sepolia token info is undefined

**Comment by phaitonican** [comment]
I also have trouble adding/finding my ERC20 token in search bar. Just can't add my token on sepolia testnetwork.
