### ISSUE TITLE
Chrome Extension (1.5.0.3) in Brave Browser is crashing after password.

### ISSUE THREAD

**Issue by zeroflaw** [Uniswap/interface#7773]
Seems after an update to 1.5.0.3 my Uniswap Extension is crashing in the Brave Browser.
I tested it using Chrome, and it seems okay. 

"Uh oh! Something crashed." is all I get on the Brave Browser. 
Where would I locate the logs to share?

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Q (DappRequestTypes.ts:264:38)

**Comment by zeroflaw** [comment]
Reinstalling the extension got it starting again. Once I reconnected to Hyperliquid, it started crashing again.

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@zeroflaw 
Support.
  {c}2024

**Comment by zeroflaw** [comment]
Support Told me you don't support the Brave Browser. But i've been using it since June without issue.
Extension works for wormhole portal, gTrade, GMX. Only website causing the unrecoverable crash loop is hyperliquid.

Still broken in 1.6.0.3.

**Comment by case-hub** [comment]
Visit the support page to report your error

**Comment by zeroflaw** [comment]
fixed in 1.7.0.4

Thank You!
