### ISSUE TITLE
Smart accounts locked out of Permit2

### ISSUE THREAD

**Issue by borislav-itskov** [Uniswap/interface#7780]
## Issue:

The `https://trading-api-labs.interface.gateway.uniswap.org/v1/swap` route has a signature input validation that requires the signature to have a fixed length of 130, as the regex suggests:

```
"\"signature\" with value \"0x777e1e52714fde949ca2c64f1f787d2a50fcf24712bf6bd10b1b0cdc9f2db87e7efde13572eadbda9340c7170c0cd4e6398fdbf65879caacbfdf5cb8bf19fd3b1b00\" fails to match the required pattern: /^0x[a-fA-F0-9]{130}$/"
```

This breaks smart accounts signatures as they can vary in length. As we all know, smart accounts have their own EIP-1271 used as a signature validation and it's not required for their signature to be 65 bytes

## Solution:  

Remove the length validation entirely as it constraints valid signature use cases

**Comment by cartcrom** [comment]
fixed, thanks for reporting!
